/* Industrial Neural Lab v9 · UI, didáctica y conexión industrial */
Object.assign(InfoLibrary,{
  neuron:{title:'Neurona artificial',formula:'zⱼ = Σᵢ wᵢⱼxᵢ + bⱼ\naⱼ = f(zⱼ)',text:'Una neurona combina entradas ponderadas, agrega un bias y aplica una función de activación.',use:'Transforma información de la capa anterior para que la red pueda representar relaciones no lineales.',variables:{'xᵢ':'entrada i','wᵢⱼ':'peso entre la entrada i y la neurona j','bⱼ':'bias de la neurona j','zⱼ':'suma ponderada','f':'función de activación','aⱼ':'salida de la neurona'},example:'Vibración, temperatura y horas de operación pueden combinarse para generar una señal interna asociada al riesgo de falla.',error:'Interpretar una activación individual como una causa. Es una transformación matemática del modelo.'},
  architecture:{...InfoLibrary.architecture,formula:'n₀ → n₁ → n₂ → … → nₗ\nParámetros entre capas = nₗ₋₁·nₗ + nₗ',use:'Define cuánta capacidad tiene la red para transformar las variables.',variables:{'n₀':'número de entradas','nₗ':'neuronas de la capa l','L':'número total de capas'},error:'Agregar muchas capas o neuronas sin revisar validation; más grande no implica mejor.'},
  training:{...InfoLibrary.training,formula:'wᵢⱼ ← wᵢⱼ − η · ∂L/∂wᵢⱼ',use:'Ajusta pesos para reducir la función de pérdida en Train.',variables:{'wᵢⱼ':'peso','η':'learning rate','L':'función de pérdida','∂L/∂wᵢⱼ':'gradiente del error respecto del peso'},error:'Evaluar calidad solo con Train. Validation y Test existen para medir generalización.'},
  backprop:{...InfoLibrary.backprop,use:'Calcula cómo debe cambiar cada parámetro usando la regla de la cadena.',variables:{'L':'pérdida','wᵢⱼ':'peso','δˡ':'sensibilidad de la capa l','f′(z)':'derivada de la activación'},error:'Pensar que el error viaja literalmente hacia atrás. Lo que se propaga son gradientes/sensibilidades.'},
  lossfunctions:{...InfoLibrary.lossfunctions,formula:'MSE = (1/n) Σᵢ₌₁ⁿ (yᵢ − ŷᵢ)²\nRMSE = √MSE\nMAE = (1/n) Σᵢ₌₁ⁿ |yᵢ − ŷᵢ|\nBCE = −(1/n) Σ [y log ŷ + (1−y)log(1−ŷ)]',use:'La loss guía el entrenamiento; las métricas traducen el rendimiento a una interpretación útil.',variables:{'yᵢ':'valor real','ŷᵢ':'predicción','n':'cantidad de observaciones','L':'función de pérdida'},error:'Comparar métricas sin considerar la unidad, escala y costo industrial del error.'},
  stats:{...InfoLibrary.stats,use:'Describe distribución, dispersión y forma antes de modelar.',variables:{'x̄':'media','s':'desviación estándar','Q1/Q3':'cuartiles','IQR':'Q3−Q1'},error:'Eliminar outliers solo porque están lejos del resto; primero hay que investigar si son errores o eventos reales.'}
});
for(const [k,v] of Object.entries(InfoLibrary)){v.use=v.use||'Ayuda a entender y configurar correctamente el modelo.';v.variables=v.variables||{};v.error=v.error||'Interpretar el concepto fuera del contexto de los datos o sin revisar sus supuestos.'}

const V9={viewTitles:{home:['INICIO','Laboratorio de decisión industrial'],data:['DATOS','Problema, X/Y y preparación'],networks:['MODELO','Arquitectura de red neuronal'],train:['ENTRENAMIENTO','Aprendizaje paso a paso'],results:['RESULTADOS','Métricas e interpretación'],analysis:['ANÁLISIS','Diagnóstico del modelo'],decision:['DECISIÓN','Conexión con Ingeniería Civil Industrial'],generalization:['GENERALIZACIÓN','Overfitting y mitigación'],stats:['ESTADÍSTICA','Análisis aplicado'],advanced:['AVANZADO','Augmentation, GAN y comparación'],concepts:['TEORÍA','Influencia, memoria y optimizadores'],lab75:['LAB 7.5','Laboratorios especializados']},dialogCallback:null,tableSort:null,tableSortDir:1};
State.animationSpeed=1;State.animPaused=false;State.studyLevel='intermediate';State.optimizerVisibility={};State.columnMeta={};State.tableSearch='';State.importance=[];

function notify(message,type='info'){
  let host=document.getElementById('toastHost');if(!host){host=document.createElement('div');host.id='toastHost';host.className='toast-host';document.body.appendChild(host)}
  const t=document.createElement('div');t.className='toast '+type;t.textContent=message;host.appendChild(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),220)},3600)
}
function openInputDialog(title,label,initial,callback){V9.dialogCallback=callback;$('inputDialogTitle').textContent=title;$('inputDialogLabel').firstChild.textContent=label;$('inputDialogValue').value=initial||'';$('inputDialog').classList.add('open');setTimeout(()=>$('inputDialogValue').focus(),30)}
function closeInputDialog(){V9.dialogCallback=null;$('inputDialog').classList.remove('open')}

function setupInfoSystem(){
  const modal=$('infoModal');
  document.addEventListener('click',e=>{const btn=e.target.closest('[data-info]');if(!btn)return;e.stopPropagation();const d=InfoLibrary[btn.dataset.info];if(!d)return;$('infoCategory').textContent=(btn.dataset.info||'concepto').toUpperCase();$('infoTitle').textContent=d.title;$('infoFormula').textContent=d.formula||'';$('infoText').textContent=d.text||'';$('infoUse').textContent=d.use||'';$('infoVariables').innerHTML=Object.entries(d.variables||{}).map(([k,v])=>`<div class="symbol-row"><b>${esc(k)}</b><span>${esc(v)}</span></div>`).join('')||'<span class="note">Sin símbolos adicionales.</span>';$('infoExample').textContent=(d.example||'').replace(/^Ejemplo:\s*/i,'');$('infoError').textContent=d.error||'';modal.classList.add('open')});
  $('closeInfoBtn').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')}
}

function activateTab(tab){
  document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-page').forEach(p=>p.classList.remove('active'));const page=$('tab-'+tab);if(page)page.classList.add('active');
  const title=V9.viewTitles[tab]||['LAB','Industrial Neural Lab'];$('viewEyebrow').textContent=title[0];$('viewTitle').textContent=title[1];$('sidebar').classList.remove('open');
  if(tab==='networks')setTimeout(renderCurrentNetwork,30);if(tab==='stats'){populateStats();renderStatsRecommendation()}if(tab==='advanced')renderComparison();if(tab==='concepts'){renderInfluence();renderMemoryTheory();renderOptimizerFormula();renderOptimizerVisibility()}if(tab==='lab75'){renderCategoricalAudit();populateSequenceColumns();renderThresholdLab();renderMulticlassTargetAudit()}if(tab==='decision')updateDecisionPanel();if(tab==='results')updateResultBacks();window.scrollTo({top:0,behavior:'smooth'});
}
function setupNav(){document.addEventListener('click',e=>{const nav=e.target.closest('.nav-btn[data-tab], [data-go]');if(!nav)return;const tab=nav.dataset.tab||nav.dataset.go;if(tab)activateTab(tab)});$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open')}
function setStudyLevel(level){State.studyLevel=level;document.documentElement.dataset.study=level;document.querySelectorAll('[data-study-level]').forEach(b=>b.classList.toggle('primary',b.dataset.studyLevel===level));try{localStorage.setItem('inl-study',level)}catch(e){}notify(`Nivel ${level==='basic'?'Básico':level==='advanced'?'Avanzado':'Intermedio'} activado.`)}
function toggleTheme(){const d=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=d;try{localStorage.setItem('lab-theme',d)}catch(e){}setTimeout(()=>{renderCurrentNetwork();renderStats();renderCorrelation();const t=currentNet()?.trained;if(t){drawLoss(t.trainHist,t.valHist);drawLearningCurve(t.trainHist,t.valHist);if(t.preds)drawParity($('predChart'),t.preds.y,t.preds.p)}},20)}

function columnProfile(name,rows){
  const raw=rows.map(r=>r[name]),vals=raw.filter(v=>v!==''&&v!=null),labels=vals.map(v=>String(v).trim()),nums=vals.map(Number).filter(Number.isFinite),numeric=vals.length?nums.length/vals.length>=.85:false,unique=[...new Set(labels)],uniqueCount=unique.length,uniqueRatio=vals.length?uniqueCount/vals.length:0;
  const dateHits=labels.filter(v=>!numeric&&/^\d{4}[-/]\d{1,2}[-/]\d{1,2}|^\d{1,2}[-/]\d{1,2}[-/]\d{2,4}/.test(v)&&!Number.isNaN(Date.parse(v))).length,date=dateHits>=Math.max(2,labels.length*.7),integerLike=numeric&&nums.every(v=>Math.abs(v-Math.round(v))<1e-9),binary=uniqueCount===2,missing=raw.length-vals.length;
  const lower=name.toLowerCase(),looksId=/^(id|id_|codigo|código|code|folio|serial|nro|numero|número|registro|equipo_id|cliente_id)/.test(lower)||/_id$/.test(lower)||((/id|codigo|serial/.test(lower))&&uniqueRatio>.75);
  let type=date?'fecha':numeric?(binary?'binaria':'numérica'):(binary?'binaria/categórica':'categórica');return{name,vals,labels,numeric,nums,uniqueCount,uniqueRatio,integerLike,binary,nonEmpty:vals.length,missing,date,looksId,type,unique}
}
function detectIndustrialContext(columns,yName=''){
  const t=(columns.join(' ')+' '+(yName||'')).toLowerCase();
  const areas=[
    ['Confiabilidad y mantenimiento',[[/falla|failure|fault|mtbf|mttr|mantenimiento|downtime|availability|disponibilidad|confiabilidad|rul|vida_util/g,4],[/vibr/g,2],[/temperat|presion/g,.5]]],
    ['Producción',[[/produccion|producción|oee|tiempo_ciclo|ciclo|capacidad|cuello|linea|línea|turno|rendimiento|productividad|throughput/g,3],[/velocidad/g,1]]],
    ['Calidad de procesos',[[/calidad|defecto|rechazo|scrap|merma|inspeccion|grieta|tolerancia/g,4],[/humedad|proceso/g,1]]],
    ['Transporte y logística',[[/ruta|distancia|viaje|flota|camion|camión|entrega|transporte|congestion|sla|retraso/g,3],[/carga/g,1]]],
    ['Ingeniería económica',[[/costo|ingreso|beneficio|precio|flujo|van|tir|payback|rentabilidad|utilidad|inversion|inversión/g,3],[/demanda/g,1]]],
    ['Inventario',[[/inventario|stock|quiebre|lead.?time|reorden|bodega|sku/g,4],[/demanda/g,1]]],
    ['Investigación Operativa',[[/plem|vrp|scheduling|asignacion|asignación|ruteo|programacion|programación|restriccion|restricción|tiempo_servicio|prioridad/g,4],[/capacidad/g,1]]],
    ['RRHH y dotación',[[/ausentismo|dotacion|dotación|turnover|rotacion|rotación|empleado|horas_extra/g,4]]]
  ];
  let best=['Analítica industrial general',0];
  for(const [name,groups] of areas){let score=0;for(const [re,w] of groups){const m=t.match(re);if(m)score+=m.length*w}if(score>best[1])best=[name,score]}
  return best[0]
}
function inferUnit(name){const n=name.toLowerCase();if(/ton[_\/ -]?h|tonelad.*hora|produccion.*ton.*h/.test(n))return'ton/h';if(/kwh|energia.*kw/.test(n))return'kWh';if(/mm[_\/ -]?s|vibracion.*mm/.test(n))return'mm/s';if(/rpm/.test(n))return'RPM';if(/minuto|_min$|tiempo.*min/.test(n))return'min';if(/hora|_h$|hours|hr/.test(n))return'h';if(/temperat/.test(n))return'°C';if(/presion|presión/.test(n))return'bar';if(/porcentaje|pct|tasa|ratio|_pct/.test(n))return'%';if(/kg|peso/.test(n))return'kg';if(/precio|costo|ingreso|flujo|utilidad|van/.test(n))return'$';if(/distancia|km/.test(n))return'km';return''}
function detectPotentialLeakage(rows,columns,y,profiles){if(!y)return[];const leaks=[],yp=profiles.find(p=>p.name===y);columns.forEach(c=>{if(c===y)return;const p=profiles.find(q=>q.name===c),n=c.toLowerCase();if(/post|despues|después|resultado_final|target|label|salida_real|outcome/.test(n))leaks.push({column:c,reason:'El nombre sugiere información disponible después del resultado.'});if(yp?.numeric&&p?.numeric){const pairs=rows.map(r=>[Number(r[c]),Number(r[y])]).filter(v=>v.every(Number.isFinite));if(pairs.length>8){const rr=Math.abs(corr(pairs.map(v=>v[0]),pairs.map(v=>v[1])));if(rr>.995)leaks.push({column:c,reason:`Correlación casi perfecta con Y (|r|=${rr.toFixed(3)}); revisar posible fuga.`})}}});return leaks.slice(0,8)}
function suggestSchema(rows,columns){
  const profs=columns.map(c=>columnProfile(c,rows)),roles={};columns.forEach(c=>roles[c]='X');const scoreRows=[];
  profs.forEach((p,idx)=>{const n=p.name.toLowerCase();let s=0,reasons=[];if(/target|objetivo|salida|resultado|label|class|clase|defecto|falla|fault|failure|flujo_neto|flujo.*net|tiempo_viaje|tiempo_servicio|tiempo_ciclo|rul|quiebre|ausentismo|scrap|oee/.test(n)){s+=14;reasons.push('el nombre parece describir un resultado final')}else if(/calidad|indice|índice|score|demanda|costo|tiempo|riesgo|disponibilidad|flujo|utilidad/.test(n)){s+=7;reasons.push('el nombre puede representar un resultado')}if(p.binary){s+=5;reasons.push('tiene dos valores posibles')}if(!p.numeric&&!p.date&&p.uniqueCount>=3&&p.uniqueCount<=12){s+=4;reasons.push('tiene pocas categorías')}if(p.numeric&&p.uniqueCount>6){s+=2}if(idx===columns.length-1)s+=1;if(p.looksId){s-=100;reasons=['parece un identificador, no un objetivo']}if(p.uniqueRatio>.98&&p.nonEmpty>20&&!p.numeric){s-=8}if(p.date)s-=3;scoreRows.push({name:p.name,score:s,reasons})});
  scoreRows.sort((a,b)=>b.score-a.score);let best=scoreRows[0],y=best?.name||columns[0]||null,confidence=best?.score>=8?'alta':best?.score>=4?'media':'baja';if(y)roles[y]='Y';const excluded=[];profs.forEach(p=>{if(p.name!==y&&p.looksId){roles[p.name]='Excluir';excluded.push(p.name)}});
  const yProf=profs.find(p=>p.name===y)||{numeric:true,binary:false,uniqueCount:0,integerLike:false};let mode='regresión';if(yProf.binary)mode='clasificación binaria';else if(!yProf.numeric&&!yProf.date)mode='multiclase';else if(yProf.integerLike&&yProf.uniqueCount>=3&&yProf.uniqueCount<=15)mode='multiclase';
  const xNames=columns.filter(c=>roles[c]==='X'),xCount=xNames.length,context=detectIndustrialContext(columns,y),hidden=xCount<=3?[4]:xCount<=8?[Math.min(8,xCount+3),4]:[Math.min(16,Math.max(8,xCount+2)),8,4],optimizer=/Confiabilidad|Calidad/.test(context)?'adamw':'adam',loss=mode==='regresión'?'Huber o MSE':mode==='clasificación binaria'?'Binary Cross-Entropy':'Cross-Entropy + Softmax';
  const metrics=mode==='regresión'?['MAE','RMSE','R²']:context.includes('Confiabilidad')?['Recall','F1','Precision']:['F1','Precision','Recall','Accuracy'],leakage=detectPotentialLeakage(rows,columns,y,profs);
  const why=context.includes('Confiabilidad')&&mode!=='regresión'?'En mantenimiento predictivo suele importar detectar fallas reales y revisar falsos negativos.':mode==='regresión'?'MAE traduce el error a unidades reales y RMSE da más peso a errores grandes.':'F1, Precision y Recall permiten separar tipos de error mejor que Accuracy sola.';
  return{roles,y,yProf,mode,context,excluded,xCount,hidden,optimizer,loss,metrics,why,profiles:profs,targetReasons:best?.reasons||[],confidence,leakage,scoreRows}
}
function auditDataset(){
  const rows=State.rows,profiles=State.columns.map(c=>columnProfile(c,rows)),missing=profiles.reduce((s,p)=>s+p.missing,0),seen=new Map(),duplicates=new Set();rows.forEach((r,i)=>{const k=JSON.stringify(State.columns.map(c=>r[c]));if(seen.has(k)){duplicates.add(i);duplicates.add(seen.get(k))}else seen.set(k,i)});const outlierCells=new Set();profiles.filter(p=>p.numeric&&p.nums.length>=8).forEach(p=>{const q1=quantile(p.nums,.25),q3=quantile(p.nums,.75),iqr=q3-q1,lo=q1-1.5*iqr,hi=q3+1.5*iqr;rows.forEach((r,i)=>{const v=Number(r[p.name]);if(Number.isFinite(v)&&(v<lo||v>hi))outlierCells.add(`${i}|${p.name}`)})});const invalid=new Set();profiles.forEach(p=>{if(!p.numeric)return;rows.forEach((r,i)=>{const v=r[p.name];if(v!==''&&v!=null&&!Number.isFinite(Number(v)))invalid.add(`${i}|${p.name}`)})});return{profiles,missing,duplicates,outlierCells,invalid,categorical:profiles.filter(p=>!p.numeric&&!p.date).length,ids:profiles.filter(p=>p.looksId).length}}
function renderAudit(){const a=auditDataset();State.audit=a;if($('datasetAudit'))$('datasetAudit').innerHTML=[['Faltantes',a.missing,a.missing?'warn':''],['Duplicados',Math.max(0,a.duplicates.size?Math.ceil(a.duplicates.size/2):0),a.duplicates.size?'warn':''],['Posibles outliers',a.outlierCells.size,a.outlierCells.size?'warn':''],['Categóricas',a.categorical,''],['IDs detectados',a.ids,''],['Inválidos',a.invalid.size,a.invalid.size?'bad':'']].map(([k,v,c])=>`<div class="audit-item ${c}"><span>${k}</span><b>${v}</b></div>`).join('')}
function renderTargetReasoning(){const box=$('targetReasoning');if(!box||!State.schema)return;const s=State.schema;box.innerHTML=`<div class="reason-line"><strong>Creemos que Y podría ser: ${esc(s.y||'—')}</strong><br><span>Confianza ${esc(s.confidence)} · ${esc(s.targetReasons.join('; ')||'no hay una señal fuerte; revisa la sugerencia manualmente')}</span></div><div class="schema-columns">${State.columns.slice(0,16).map(c=>`<div class="schema-row"><span>${esc(c)} <small>· ${esc((s.profiles.find(p=>p.name===c)||{}).type||'')}</small></span><span class="role-chip role-${(s.roles[c]||'X').toLowerCase().replace('excluir','excluir')}">${esc(s.roles[c]||'X')}</span></div>`).join('')}</div>${s.leakage.length?`<div class="diagnosis-box warn"><strong>Posible fuga de información</strong><br>${s.leakage.map(x=>`${esc(x.column)}: ${esc(x.reason)}`).join('<br>')}</div>`:''}`}
function renderDatasetGuide(){
  const box=$('datasetGuide');if(!box)return;if(!State.rows.length){box.textContent='Sube un CSV para iniciar.';return}State.schema=suggestSchema(State.rows,State.columns);const s=State.schema,recArch=[Math.max(1,s.xCount),...s.hidden,1].join(' → '),ids=s.profiles.filter(p=>p.looksId).map(p=>p.name),xs=State.columns.filter(c=>s.roles[c]==='X');
  box.innerHTML=`<article class="guide-card guide-hero"><span class="kicker">PROBLEMA DETECTADO</span><h3>${esc(s.context)}</h3><p><b>${esc(s.mode)}</b>. Esto es una sugerencia automática: tú puedes cambiar Y, X, loss y arquitectura.</p><div class="pill-row"><span class="pill">${State.rows.length.toLocaleString('es-CL')} filas</span><span class="pill">${State.columns.length} variables</span><span class="pill">Confianza Y: ${esc(s.confidence)}</span></div></article><article class="guide-card"><span class="kicker">OBJETIVO</span><h3>${esc(s.y||'—')}</h3><p>${esc(s.targetReasons.join('. ')||'Revisa manualmente por qué esta columna debería ser el resultado.')}</p><p><b>IDs:</b> ${ids.length?esc(ids.join(', ')):'ninguno evidente'}</p></article><article class="guide-card"><span class="kicker">X SUGERIDAS</span><h3>${xs.length} variables</h3><p>${esc(xs.slice(0,7).join(', '))}${xs.length>7?'…':''}</p></article><article class="guide-card"><span class="kicker">MODELO INICIAL</span><h3>MLP · ${recArch}</h3><p><b>Loss:</b> ${esc(s.loss)}<br><b>Optimizador:</b> ${esc(s.optimizer.toUpperCase())}</p></article><article class="guide-card"><span class="kicker">MÉTRICAS</span><h3>${s.metrics.join(' · ')}</h3><p>${esc(s.why)}</p></article><article class="guide-card"><span class="kicker">DECISIÓN</span><h3>Predicción como insumo</h3><p>Usa el modelo para formular preguntas y alimentar optimización o evaluación económica; no como una orden automática.</p></article>`;
  if($('homeProblem'))$('homeProblem').textContent=s.context;if($('homeRows'))$('homeRows').textContent=State.rows.length.toLocaleString('es-CL');if($('homeCols'))$('homeCols').textContent=State.columns.length;if($('homeTarget'))$('homeTarget').textContent=s.y||'—';renderTargetReasoning();renderAudit();renderHomeNetwork();renderColumnWorkbench();markFlowState()
}
function renderHomeNetwork(){const svg=$('homeNetworkSvg');if(!svg||!State.schema)return;svg.innerHTML='';const sizes=[Math.max(1,Math.min(5,State.schema.xCount)),...State.schema.hidden.map(x=>Math.min(x,5)),1],W=760,H=230,r=14,x=i=>65+i*(W-130)/Math.max(1,sizes.length-1),ys=c=>Array.from({length:c},(_,j)=>H/2+(j-(c-1)/2)*Math.min(36,150/Math.max(1,c-1||1))),NS='http://www.w3.org/2000/svg',mk=(tag,a)=>{const e=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));svg.appendChild(e);return e};const pos=sizes.map((s,i)=>ys(s).map(y=>[x(i),y]));for(let l=0;l<pos.length-1;l++)pos[l].forEach(a=>pos[l+1].forEach(b=>mk('line',{x1:a[0]+r,y1:a[1],x2:b[0]-r,y2:b[1],stroke:cssVar('--line'), 'stroke-width':1})));pos.forEach((layer,li)=>layer.forEach(([cx,cy])=>mk('circle',{cx,cy,r,fill:cssVar('--surface'),stroke:li===0?cssVar('--steel'):li===pos.length-1?cssVar('--emerald'):cssVar('--violet'),'stroke-width':2})))}

function loadData(rows){State.rows=JSON.parse(JSON.stringify(rows||[]));State.originalRows=JSON.parse(JSON.stringify(rows||[]));State.columns=Object.keys(rows?.[0]||{});State.columnMeta={};State.columns.forEach(c=>State.columnMeta[c]={type:columnProfile(c,State.rows).type,unit:inferUnit(c)});State.schema=suggestSchema(State.rows,State.columns);State.roles={...State.schema.roles};State.tableSearch='';renderTable();populateStats();populateGan();applySplit();renderCategoricalAudit();populateSequenceColumns();renderMulticlassTargetAudit();renderDatasetGuide();const y=targetY();if(y){const p=columnProfile(y,State.rows);updateLossUI(p.binary)}renderCurrentNetwork();markFlowState()}
function applySuggestedRoles(){if(!State.rows.length)return;State.schema=suggestSchema(State.rows,State.columns);State.roles={...State.schema.roles};renderTable();applySplit();populateStats();renderCategoricalAudit();populateSequenceColumns();renderMulticlassTargetAudit();renderDatasetGuide();renderCurrentNetwork();notify('Configuración X/Y aplicada. Puedes editarla en cualquier momento.','success')}
function applyRecommendedNetwork(){if(!State.schema)State.schema=suggestSchema(State.rows,State.columns);const n=currentNet();if(!n)return;n.hidden=State.schema.hidden.slice();n.hiddenActivation=State.schema.mode==='regresión'?'tanh':'relu';n.initMethod=n.hiddenActivation==='relu'?'he':'xavier';n.layerSettings=n.hidden.map(()=>({activation:n.hiddenActivation,dropout:0,batchNorm:false,bias:true}));$('optimizer').value=State.schema.optimizer;$('lossFunction').value='auto';renderCurrentNetwork();notify('Arquitectura inicial aplicada. Es una base para experimentar, no una arquitectura óptima.','success')}

function renderTable(){
  const t=$('dataTable');if(!t)return;t.innerHTML='';if(!State.columns.length)return;const a=State.audit||auditDataset(),q=(State.tableSearch||'').toLowerCase(),indices=State.rows.map((r,i)=>i).filter(i=>!q||State.columns.some(c=>String(State.rows[i][c]??'').toLowerCase().includes(q)));if(V9.tableSort){indices.sort((ia,ib)=>{const A=State.rows[ia][V9.tableSort],B=State.rows[ib][V9.tableSort],na=Number(A),nb=Number(B),v=Number.isFinite(na)&&Number.isFinite(nb)?na-nb:String(A??'').localeCompare(String(B??''),'es');return v*V9.tableSortDir})}
  const th=document.createElement('thead'),tr=document.createElement('tr');tr.innerHTML='<th>#</th>';State.columns.forEach(c=>{const x=document.createElement('th');const p=columnProfile(c,State.rows);x.innerHTML=`<div class="th-main"><button class="th-sort" data-sort="${esc(c)}" title="Ordenar">${esc(c)}</button><small>${esc(State.columnMeta?.[c]?.unit||'')} ${esc(p.type)}</small></div><select data-role="${esc(c)}" aria-label="Rol de ${esc(c)}"><option ${State.roles[c]==='X'?'selected':''}>X</option><option ${State.roles[c]==='Y'?'selected':''}>Y</option><option ${State.roles[c]==='Excluir'?'selected':''}>Excluir</option></select>`;tr.appendChild(x)});tr.innerHTML+='<th></th>';th.appendChild(tr);t.appendChild(th);const tb=document.createElement('tbody');indices.slice(0,500).forEach(ri=>{const r=State.rows[ri],row=document.createElement('tr');if(a.duplicates?.has(ri))row.classList.add('row-duplicate');row.innerHTML=`<td>${ri+1}${r.__syn?'*':''}</td>`;State.columns.forEach((c,ci)=>{const td=document.createElement('td'),v=r[c],key=`${ri}|${c}`,classes=[];if(v===''||v==null)classes.push('cell-missing');if(a.outlierCells?.has(key))classes.push('cell-outlier');if(a.invalid?.has(key))classes.push('cell-invalid');td.className=classes.join(' ');td.innerHTML=`<input data-r="${ri}" data-ci="${ci}" data-c="${esc(c)}" value="${esc(v)}" aria-label="Fila ${ri+1}, ${esc(c)}">`;row.appendChild(td)});row.innerHTML+=`<td><button class="icon-btn row-delete" data-del="${ri}" title="Eliminar fila"><svg><use href="#i-close"/></svg></button></td>`;tb.appendChild(row)});if(indices.length>500){const nr=document.createElement('tr');nr.innerHTML=`<td colspan="${State.columns.length+2}">Se muestran 500 de ${indices.length} filas coincidentes.</td>`;tb.appendChild(nr)}t.appendChild(tb);
  t.querySelectorAll('[data-r]').forEach(i=>{i.onchange=()=>{const n=Number(i.value);State.rows[+i.dataset.r][i.dataset.c]=Number.isFinite(n)&&i.value.trim()!==''?n:i.value;State.audit=auditDataset();populateStats();populateGan();renderDatasetGuide();renderTable()};i.onpaste=e=>handleTablePaste(e,i)});t.querySelectorAll('[data-role]').forEach(s=>s.onchange=()=>{if(s.value==='Y')Object.keys(State.roles).forEach(k=>{if(State.roles[k]==='Y')State.roles[k]='X'});State.roles[s.dataset.role]=s.value;renderTable();renderCurrentNetwork();populateStats();renderMulticlassTargetAudit();renderDatasetGuide();applySplit()});t.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{State.rows.splice(+b.dataset.del,1);State.audit=auditDataset();renderTable();applySplit();renderDatasetGuide();populateStats()});t.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{if(V9.tableSort===b.dataset.sort)V9.tableSortDir*=-1;else{V9.tableSort=b.dataset.sort;V9.tableSortDir=1}renderTable()});if($('tableFilterStatus'))$('tableFilterStatus').textContent=q?`${indices.length} filas coinciden`:`${State.rows.length} filas`;renderAudit()
}
function handleTablePaste(e,input){const text=e.clipboardData?.getData('text');if(!text||(!text.includes('\t')&&!text.includes('\n')))return;e.preventDefault();const grid=text.replace(/\r/g,'').split('\n').filter((x,i,a)=>x!==''||i<a.length-1).map(r=>r.split('\t')),r0=+input.dataset.r,c0=+input.dataset.ci;grid.forEach((row,dr)=>row.forEach((v,dc)=>{const ri=r0+dr,ci=c0+dc;if(ri<State.rows.length&&ci<State.columns.length){const n=Number(v);State.rows[ri][State.columns[ci]]=Number.isFinite(n)&&v.trim()!==''?n:v}}));State.audit=auditDataset();renderTable();renderDatasetGuide();populateStats();notify(`Pegadas ${grid.length} fila(s) desde el portapapeles.`,'success')}
function addRow(){const o={};State.columns.forEach(c=>o[c]='');State.rows.push(o);State.audit=auditDataset();renderTable();applySplit();renderDatasetGuide()}
function addColumn(){openInputDialog('Agregar columna','Nombre de columna','',name=>{name=name.trim();if(!name||State.columns.includes(name)){notify('Usa un nombre nuevo para la columna.','warning');return}State.columns.push(name);State.roles[name]='X';State.columnMeta[name]={type:'numérica',unit:''};State.rows.forEach(r=>r[name]='');State.audit=auditDataset();renderTable();populateStats();renderDatasetGuide();renderCurrentNetwork()})}
function renderColumnWorkbench(){const box=$('columnWorkbench');if(!box)return;box.innerHTML=`<div class="column-meta-grid">${State.columns.map(c=>{const p=columnProfile(c,State.rows),m=State.columnMeta[c]||{type:p.type,unit:inferUnit(c)};State.columnMeta[c]=m;return`<div class="column-meta-card"><strong>${esc(c)}</strong><small>${esc(p.type)} · ${p.uniqueCount} valores distintos</small><div class="controls-grid compact"><label>Tipo<select data-col-type="${esc(c)}"><option ${m.type==='numérica'?'selected':''}>numérica</option><option ${m.type.includes('categ')?'selected':''}>categórica</option><option ${m.type==='fecha'?'selected':''}>fecha</option></select></label><label>Unidad<input data-col-unit="${esc(c)}" value="${esc(m.unit||'')}"></label></div><div class="actions"><button data-col-rename="${esc(c)}">Renombrar</button><button data-col-delete="${esc(c)}">Eliminar</button></div></div>`}).join('')}</div>`;box.querySelectorAll('[data-col-type]').forEach(s=>s.onchange=()=>State.columnMeta[s.dataset.colType].type=s.value);box.querySelectorAll('[data-col-unit]').forEach(i=>i.onchange=()=>State.columnMeta[i.dataset.colUnit].unit=i.value);box.querySelectorAll('[data-col-rename]').forEach(b=>b.onclick=()=>renameColumn(b.dataset.colRename));box.querySelectorAll('[data-col-delete]').forEach(b=>b.onclick=()=>deleteColumn(b.dataset.colDelete))}
function renameColumn(old){openInputDialog('Renombrar columna','Nuevo nombre',old,name=>{name=name.trim();if(!name||name===old)return;if(State.columns.includes(name)){notify('Ya existe una columna con ese nombre.','warning');return}State.columns=State.columns.map(c=>c===old?name:c);State.rows.forEach(r=>{r[name]=r[old];delete r[old]});State.roles[name]=State.roles[old];delete State.roles[old];State.columnMeta[name]=State.columnMeta[old]||{};delete State.columnMeta[old];renderTable();populateStats();renderDatasetGuide();renderCurrentNetwork()})}
function deleteColumn(c){if(State.columns.length<=2){notify('Conserva al menos dos columnas.','warning');return}State.columns=State.columns.filter(x=>x!==c);State.rows.forEach(r=>delete r[c]);delete State.roles[c];delete State.columnMeta[c];if(!targetY()){const s=suggestSchema(State.rows,State.columns);State.roles={...s.roles}}renderTable();populateStats();renderDatasetGuide();renderCurrentNetwork()}
function renameCurrentNetwork(){openInputDialog('Renombrar red','Nombre',currentNet().name,name=>{if(name.trim()){currentNet().name=name.trim();renderNetworkTabs();renderCurrentNetwork()}})}

function newNetwork(name){State.networks.push({name,hidden:[6,4],hiddenActivation:'relu',outputActivation:'auto',initMethod:'he',layerSettings:[{activation:'relu',dropout:0,batchNorm:false,bias:true},{activation:'relu',dropout:0,batchNorm:false,bias:true}],trained:null});State.currentNetwork=State.networks.length-1;renderNetworkTabs();renderCurrentNetwork();markFlowState()}
function renderCurrentNetwork(){
  const n=currentNet();if(!n)return;if($('currentNetworkName'))$('currentNetworkName').textContent=n.name;if($('hiddenActivation'))$('hiddenActivation').value=n.hiddenActivation;if($('outputActivation'))$('outputActivation').value=n.outputActivation;if($('initMethod'))$('initMethod').value=n.initMethod;const le=$('layerEditor');if(!le)return;le.innerHTML='';n.layerSettings=n.layerSettings||[];while(n.layerSettings.length<n.hidden.length)n.layerSettings.push({activation:n.hiddenActivation||'relu',dropout:0,batchNorm:false,bias:true});n.layerSettings=n.layerSettings.slice(0,n.hidden.length);
  n.hidden.forEach((v,i)=>{const s={activation:n.hiddenActivation||'relu',dropout:0,batchNorm:false,bias:true,...n.layerSettings[i]},d=document.createElement('div');d.className='layer-row';d.innerHTML=`<strong>H${i+1}</strong><div><div class="layer-count"><button data-layer-minus="${i}" aria-label="Quitar neurona"><svg><use href="#i-minus"/></svg></button><strong>${v}</strong><button data-layer-plus="${i}" aria-label="Agregar neurona"><svg><use href="#i-plus"/></svg></button></div><div class="layer-options"><select data-layer-act="${i}"><option value="relu" ${s.activation==='relu'?'selected':''}>ReLU</option><option value="leaky" ${s.activation==='leaky'?'selected':''}>Leaky ReLU</option><option value="elu" ${s.activation==='elu'?'selected':''}>ELU</option><option value="tanh" ${s.activation==='tanh'?'selected':''}>tanh</option><option value="sigmoid" ${s.activation==='sigmoid'?'selected':''}>Sigmoid</option></select><input data-layer-drop="${i}" type="number" min="0" max=".8" step=".05" value="${s.dropout||0}" title="Dropout"></div><div class="layer-toggles level-advanced"><label><input type="checkbox" data-layer-bn="${i}" ${s.batchNorm?'checked':''}>BatchNorm</label><label><input type="checkbox" data-layer-bias="${i}" ${s.bias!==false?'checked':''}>Bias</label></div></div><button class="icon-btn" data-remove="${i}" title="Eliminar capa"><svg><use href="#i-close"/></svg></button>`;le.appendChild(d)});
  le.querySelectorAll('[data-layer-minus]').forEach(b=>b.onclick=()=>{const i=+b.dataset.layerMinus;n.hidden[i]=Math.max(1,n.hidden[i]-1);renderCurrentNetwork()});le.querySelectorAll('[data-layer-plus]').forEach(b=>b.onclick=()=>{const i=+b.dataset.layerPlus;n.hidden[i]=Math.min(128,n.hidden[i]+1);renderCurrentNetwork()});le.querySelectorAll('[data-layer-act]').forEach(s=>s.onchange=()=>{n.layerSettings[+s.dataset.layerAct].activation=s.value;renderNetworkVisual()});le.querySelectorAll('[data-layer-drop]').forEach(s=>s.onchange=()=>n.layerSettings[+s.dataset.layerDrop].dropout=Math.max(0,Math.min(.8,+s.value||0)));le.querySelectorAll('[data-layer-bn]').forEach(s=>s.onchange=()=>{n.layerSettings[+s.dataset.layerBn].batchNorm=s.checked;if(s.checked)notify('BatchNorm queda registrado como configuración experimental; el motor JS ligero no altera el cálculo con BatchNorm.','warning')});le.querySelectorAll('[data-layer-bias]').forEach(s=>s.onchange=()=>{n.layerSettings[+s.dataset.layerBias].bias=s.checked});le.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const i=+b.dataset.remove;n.hidden.splice(i,1);n.layerSettings.splice(i,1);renderCurrentNetwork()});renderNetworkVisual();renderPredictor();markFlowState()
}
function addLayer(){const n=currentNet();n.hidden.push(4);n.layerSettings.push({activation:n.hiddenActivation||'relu',dropout:0,batchNorm:false,bias:true});renderCurrentNetwork()}
function applyPreset(p){const n=currentNet();const presets={linear:[],simple:[4],medium:[8,4],deep:[16,8,4],funnel:[16,8,4],bottleneck:[12,3,12],wide:[16,12]};n.hidden=(presets[p]||presets.medium).slice();n.layerSettings=n.hidden.map(()=>({activation:n.hiddenActivation||'relu',dropout:0,batchNorm:false,bias:true}));renderCurrentNetwork()}
function forward(m,x,training=false){let acts=[x],masks=[],raws=[];const globalDropout=$('useDropout')?.checked?Math.max(0,Math.min(.9,+$('dropoutRate').value||0)):0;for(let l=0;l<m.sizes.length-2;l++){const ls=m.layerSettings?.[l]||{activation:m.hiddenActivation,dropout:globalDropout,bias:true},actType=ls.activation||m.hiddenActivation,dropout=+ls.dropout>0?+ls.dropout:globalDropout,biasOn=ls.bias!==false;let a=m.weights[l].map((row,j)=>activation(row.reduce((s,w,i)=>s+w*acts[l][i],biasOn?m.biases[l][j]:0),actType));const a0=a.slice();let mask=a.map(()=>1);if(training&&dropout>0){mask=a.map(()=>trainRand()>dropout?1/(1-dropout):0);a=a.map((v,i)=>v*mask[i])}masks.push(mask);raws.push(a0);acts.push(a)}const L=m.sizes.length-2,z=m.weights[L][0].reduce((s,w,i)=>s+w*acts[L][i],m.biases[L][0]),out=m.classification?1/(1+Math.exp(-Math.max(-40,Math.min(40,z)))):z;acts.push([out]);return{acts,masks,raws,y:out}}
function forwardTrace(m,x){let prev=x,acts=[x],layers=[];for(let l=0;l<m.sizes.length-2;l++){const ls=m.layerSettings?.[l]||{activation:m.hiddenActivation,bias:true},type=ls.activation||m.hiddenActivation,z=m.weights[l].map((row,j)=>row.reduce((s,w,i)=>s+w*prev[i],ls.bias===false?0:m.biases[l][j])),a=z.map(v=>activation(v,type));layers.push({z,a,type,biases:m.biases[l],weights:m.weights[l],prev});acts.push(a);prev=a}const L=m.sizes.length-2,zout=m.weights[L][0].reduce((s,w,i)=>s+w*prev[i],m.biases[L][0]),out=m.classification?1/(1+Math.exp(-Math.max(-40,Math.min(40,zout)))):zout;layers.push({z:[zout],a:[out],type:m.classification?'sigmoid':'linear',biases:m.biases[L],weights:m.weights[L],prev});acts.push([out]);return{acts,layers,y:out}}
function currentVisualModel(){const t=currentNet()?.trained?.model;if(t&&t.sizes?.[0]===numericX().length)return t;if(State.liveModel&&State.liveModel.sizes?.[0]===numericX().length)return State.liveModel;return null}
function nodeLayout(sizes,W=1000,H=560){const mx=82,my=72,r=25,x=i=>mx+i*((W-2*mx)/Math.max(1,sizes.length-1)),counts=sizes.map(s=>Math.min(s,8)),ys=counts.map(c=>c===1?[H/2]:Array.from({length:c},(_,j)=>my+j*((H-2*my)/(c-1))));return{r,counts,pos:counts.map((c,l)=>ys[l].map(y=>({x:x(l),y})))}}
function shortenedLine(a,b,r){const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,ux=dx/len,uy=dy/len;return{x1:a.x+ux*r,y1:a.y+uy*r,x2:b.x-ux*r,y2:b.y-uy*r}}
function renderNetworkVisual(){
  const n=currentNet();if(!n||!$('networkSvg'))return;const inputs=Math.max(1,numericX().length||State.schema?.xCount||1),sizes=[inputs,...n.hidden,1],svg=$('networkSvg');svg.innerHTML='';if($('networkLayers'))$('networkLayers').innerHTML='';$('architectureTitle').textContent=sizes.join(' → ');$('hiddenCount').textContent=n.hidden.length;$('neuronCount').textContent=n.hidden.reduce((a,b)=>a+b,0);$('activationName').textContent=n.layerSettings?.map(x=>x.activation).join(' / ')||n.hiddenActivation;let params=0;for(let i=0;i<sizes.length-1;i++)params+=sizes[i]*sizes[i+1]+sizes[i+1];$('paramCount').textContent=params;
  const W=1000,H=560,{r,counts,pos}=nodeLayout(sizes,W,H),NS='http://www.w3.org/2000/svg',model=currentVisualModel(),showWeights=$('showWeightsToggle')?.checked!==false,mk=(tag,attrs,parent=svg)=>{const e=document.createElementNS(NS,tag);Object.entries(attrs||{}).forEach(([k,v])=>e.setAttribute(k,v));parent.appendChild(e);return e};const edgeGroups=[];
  for(let l=0;l<pos.length-1;l++){edgeGroups[l]=[];const weights=model?.weights?.[l]||null,maxW=weights?Math.max(1e-9,...weights.flat().map(Math.abs)):1;pos[l].forEach((a,i)=>pos[l+1].forEach((b,j)=>{const q=shortenedLine(a,b,r),wt=weights?.[j]?.[i],cls=Number.isFinite(wt)&&showWeights?`edge ${wt>=0?'weight-pos':'weight-neg'}`:'edge',line=mk('line',{...q,class:cls,'data-edge-layer':l,'data-edge-from':i,'data-edge-to':j,'stroke-width':Number.isFinite(wt)&&showWeights?(0.7+4*Math.abs(wt)/maxW).toFixed(2):1.1,opacity:Number.isFinite(wt)&&showWeights?(.3+.65*Math.abs(wt)/maxW).toFixed(2):.42});line.onclick=e=>{e.stopPropagation();inspectConnection(l,i,j)};edgeGroups[l].push(line)}))}
  const nodeGroups=[];sizes.forEach((s,l)=>{nodeGroups[l]=[];mk('text',{x:pos[l][0]?.x||80,y:35,'text-anchor':'middle',class:'svg-layer-label'}).textContent=l===0?'ENTRADAS':l===sizes.length-1?'SALIDA':'H'+l;pos[l].forEach((p,j)=>{const g=mk('g',{class:`svg-node ${l===0?'input':l===sizes.length-1?'output':'hidden'}`,'data-layer':l,'data-node':j});mk('circle',{cx:p.x,cy:p.y,r},g);const label=l===0?(numericX()[j]||`X${j+1}`):l===sizes.length-1?'ŷ':`N${j+1}`;const text=mk('text',{x:p.x,y:p.y+4,'text-anchor':'middle'},g);text.textContent=label.length>7?`X${j+1}`:label;g.onclick=e=>{e.stopPropagation();inspectNode(l,j)};nodeGroups[l].push(g)});if(s>counts[l])mk('text',{x:pos[l][0]?.x||80,y:H-25,'text-anchor':'middle',class:'network-caption'}).textContent=`… +${s-counts[l]} neuronas`});mk('text',{x:18,y:H-12,class:'network-caption'}).textContent='Cables: signo del peso por color · grosor = |peso| · toca para inspeccionar';State.previewGraph={nodes:nodeGroups,edges:edgeGroups};mirrorTrainingSvg();setNetworkMotion(model?'Pesos reales del modelo actual. Selecciona una fila y toca una neurona o conexión.':'Arquitectura configurada. Después de entrenar, los cables mostrarán pesos reales.');
}
function mirrorTrainingSvg(){const src=$('networkSvg'),dst=$('trainingSvg');if(!src||!dst)return;dst.innerHTML=src.innerHTML;dst.querySelectorAll('.svg-node,.edge').forEach(x=>x.style.cursor='default')}
function inspectorSample(model){const rowNo=Math.max(1,Math.min(State.rows.length,+$('networkSampleRow')?.value||1)),r=State.rows[rowNo-1],raw=model.xs.map(c=>Number(r[c])),x=raw.map((v,j)=>(v-model.stats.xm[j])/model.stats.xsdev[j]),trace=forwardTrace(model,x),yRaw=Number(r[model.y]),yNorm=model.classification?(yRaw===model.stats.yhi?1:0):(yRaw-model.stats.ym)/model.stats.ys;return{rowNo,r,raw,x,trace,yRaw,yNorm}}
function inspectNode(layer,node){const box=$('networkInspector');if(!box)return;const m=currentVisualModel();if(!m){box.hidden=false;box.innerHTML=`<button class="icon-btn inspector-close" onclick="this.parentElement.hidden=true"><svg><use href="#i-close"/></svg></button><h3>${layer===0?'Entrada':'Neurona'} ${layer===0?'X'+(node+1):'H'+layer+'.N'+(node+1)}</h3><p>Entrena la red para inspeccionar activaciones y contribuciones reales.</p>`;return}const s=inspectorSample(m),tr=s.trace;if(layer===0){box.hidden=false;box.innerHTML=`<button class="icon-btn inspector-close" onclick="this.parentElement.hidden=true"><svg><use href="#i-close"/></svg></button><span class="kicker">ENTRADA</span><h3>${esc(m.xs[node]||'X'+(node+1))}</h3><p>Fila ${s.rowNo}</p><div class="summary-grid"><div><span>Valor real</span><b>${fmtN(s.raw[node])}</b></div><div><span>Normalizado</span><b>${fmtN(s.x[node])}</b></div><div><span>Unidad</span><b>${esc(State.columnMeta?.[m.xs[node]]?.unit||'—')}</b></div></div>`;return}const li=layer-1,L=tr.layers[li];if(!L||node>=L.a.length)return;const contrib=L.prev.map((v,i)=>({i,x:v,w:L.weights[node][i],xw:v*L.weights[node][i]})),sum=contrib.reduce((q,z)=>q+z.xw,0),b=L.biases[node]||0,z=L.z[node],a=L.a[node],title=layer===m.sizes.length-1?'Salida ŷ':`H${layer} · N${node+1}`;box.hidden=false;box.innerHTML=`<button class="icon-btn inspector-close" onclick="this.parentElement.hidden=true"><svg><use href="#i-close"/></svg></button><span class="kicker">NEURONA · FILA ${s.rowNo}</span><h3>${title}</h3><p>Activación: <b>${esc(L.type)}</b> · salida = <b>${fmtN(a)}</b></p><table><thead><tr><th>Entrada</th><th>x</th><th>w</th><th>x·w</th></tr></thead><tbody>${contrib.slice(0,16).map(c=>`<tr><td>${c.i+1}</td><td>${fmtN(c.x)}</td><td>${fmtN(c.w)}</td><td>${fmtN(c.xw)}</td></tr>`).join('')}</tbody></table><div class="math-display">Σxw = ${fmtN(sum)}\nb = ${fmtN(b)}\nz = ${fmtN(z)}\na = ${esc(L.type)}(z) = ${fmtN(a)}</div>`}
function inspectConnection(layer,i,j){const box=$('networkInspector'),m=currentVisualModel();if(!box)return;if(!m){box.hidden=false;box.innerHTML='<h3>Conexión</h3><p>Entrena la red para ver el peso real.</p>';return}const s=inspectorSample(m),tr=s.trace,w=m.weights[layer]?.[j]?.[i],input=tr.acts[layer]?.[i],c=input*w,from=layer===0?(m.xs[i]||`X${i+1}`):`H${layer}.N${i+1}`,to=layer===m.sizes.length-2?'ŷ':`H${layer+1}.N${j+1}`;box.hidden=false;box.innerHTML=`<button class="icon-btn inspector-close" onclick="this.parentElement.hidden=true"><svg><use href="#i-close"/></svg></button><span class="kicker">CONEXIÓN · FILA ${s.rowNo}</span><h3>${esc(from)} → ${esc(to)}</h3><div class="summary-grid"><div><span>Peso</span><b>${fmtN(w)}</b></div><div><span>Entrada</span><b>${fmtN(input)}</b></div><div><span>Contribución</span><b>${fmtN(c)}</b></div></div><div class="math-display">x · w = ${fmtN(input)} · ${fmtN(w)} = ${fmtN(c)}</div><p>${c<0?'Esta conexión redujo la suma ponderada de la neurona destino para esta fila.':'Esta conexión aumentó la suma ponderada de la neurona destino para esta fila.'}</p>`}
function updateNetworkWeights(m){if(!m)return;State.liveModel=m;const sizes=[...m.sizes],edges=$('networkSvg')?.querySelectorAll('.edge');if(!edges?.length||+$('architectureTitle')?.textContent.split(' → ')[0]!==sizes[0]){renderNetworkVisual();return}for(let l=0;l<sizes.length-1;l++){const W=m.weights[l],maxW=Math.max(1e-9,...W.flat().map(Math.abs));document.querySelectorAll(`#networkSvg .edge[data-edge-layer="${l}"]`).forEach(e=>{const i=+e.dataset.edgeFrom,j=+e.dataset.edgeTo,w=W?.[j]?.[i];if(!Number.isFinite(w))return;e.classList.toggle('weight-pos',w>=0);e.classList.toggle('weight-neg',w<0);e.style.strokeWidth=(.7+4*Math.abs(w)/maxW).toFixed(2);e.style.opacity=(.3+.65*Math.abs(w)/maxW).toFixed(2)});}mirrorTrainingSvg()}
function liveViz(m,val){updateNetworkWeights(m);const cv=$('predChart');if(!m.classification&&val.length){const q=collectPreds(m,val);cv.style.display='';drawParity(cv,q.y,q.p)}}
function sleepAnim(ms){return new Promise(async resolve=>{while(State.animPaused)await new Promise(r=>setTimeout(r,80));setTimeout(resolve,ms/Math.max(.25,State.animationSpeed||1))})}
function clearPreviewActive(){['networkSvg','trainingSvg'].forEach(id=>{const s=$(id);if(!s)return;s.querySelectorAll('.svg-node').forEach(g=>g.classList.remove('active'));s.querySelectorAll('.edge').forEach(g=>g.classList.remove('active','back'))})}
function applyActive(selector,cls='active'){['networkSvg','trainingSvg'].forEach(id=>$(id)?.querySelectorAll(selector).forEach(e=>e.classList.add(cls)))}
async function animateNetworkPass(){const m=currentVisualModel();if(!m){notify('Entrena la red o inicia un entrenamiento para animar valores reales.','warning');return}State.animBusy=true;const s=inspectorSample(m),tr=s.trace;clearPreviewActive();setNetworkMotion(`<strong>Fila ${s.rowNo}:</strong> comienza el forward con valores normalizados reales.`);for(let l=0;l<m.sizes.length;l++){if(l>0)applyActive(`.edge[data-edge-layer="${l-1}"]`);applyActive(`.svg-node[data-layer="${l}"]`);const val=l===0?tr.acts[0].slice(0,3).map(fmtN).join(', '):tr.acts[l].slice(0,3).map(fmtN).join(', ');$('phaseLabel').textContent='FORWARD';$('phaseTitle').textContent=l===0?'Entradas X':l===m.sizes.length-1?'Predicción ŷ':`Capa H${l}`;$('phaseMath').textContent=l===0?`x = [${val}${tr.acts[0].length>3?', …':''}]`:`a${l} = f(W${l}a${l-1}+b${l}) = [${val}${tr.acts[l].length>3?', …':''}]`;await sleepAnim(260)}const pred=m.classification?tr.y:tr.y*m.stats.ys+m.stats.ym,real=s.yRaw,loss=m.classification?lossValue(s.yNorm,tr.y,'bce'):(real-pred)**2;setNetworkMotion(`<strong>Loss:</strong> y = ${fmtN(real)} · ŷ = ${fmtN(pred)} · pérdida de esta fila ≈ ${fmtN(loss)}.`);$('phaseLabel').textContent='LOSS';$('phaseTitle').textContent='Comparar predicción con valor real';$('phaseMath').textContent=`y = ${fmtN(real)}\nŷ = ${fmtN(pred)}\nL ≈ ${fmtN(loss)}`;await sleepAnim(420);for(let l=m.sizes.length-2;l>=0;l--){applyActive(`.edge[data-edge-layer="${l}"]`,'back');$('phaseLabel').textContent='BACKPROP';$('phaseTitle').textContent=`Gradiente vuelve por ${l===0?'entradas':'H'+l}`;$('phaseMath').textContent='∂L/∂wᵢⱼ = sensibilidad × activación anterior';await sleepAnim(210)}$('phaseLabel').textContent='UPDATE';$('phaseTitle').textContent='El optimizador actualiza los pesos';$('phaseMath').textContent=`w ← w − η · ∂L/∂w\nη = ${+$('learningRate').value||0.03}`;await sleepAnim(320);clearPreviewActive();setNetworkMotion('Recorrido completado. Toca una neurona o cable para inspeccionar los valores de esta fila.');State.animBusy=false}
function animationStep(){const phases=['forward','loss','backprop','update'];State.animStep=(State.animStep||0)%phases.length;const p=phases[State.animStep++];clearPreviewActive();if(p==='forward'){applyActive('.svg-node[data-layer="0"]');$('phaseLabel').textContent='FORWARD';$('phaseTitle').textContent='Las X entran a la red';$('phaseMath').textContent='zⱼ = Σᵢ wᵢⱼxᵢ + bⱼ\naⱼ = f(zⱼ)'}else if(p==='loss'){$('phaseLabel').textContent='LOSS';$('phaseTitle').textContent='Se compara y con ŷ';$('phaseMath').textContent='MSE: (y − ŷ)²\nBCE: −[y log ŷ + (1−y)log(1−ŷ)]'}else if(p==='backprop'){applyActive('.edge','back');$('phaseLabel').textContent='BACKPROP';$('phaseTitle').textContent='Se calculan gradientes';$('phaseMath').textContent='∂L/∂wᵢⱼ'}else{clearPreviewActive();$('phaseLabel').textContent='UPDATE';$('phaseTitle').textContent='El optimizador cambia W y b';$('phaseMath').textContent='W ← W − η·gradiente'}}
async function playAnimation(){if(State.animBusy)return;await animateNetworkPass()}

function targetUnit(){const y=targetY();return y?(State.columnMeta?.[y]?.unit||inferUnit(y)):''}
function renderEvaluationMetrics(model,data){const box=$('evaluationMetrics');if(!box)return;box.innerHTML='';const m=model.classification?classificationMetrics(model,data):regressionMetrics(model,data),unit=targetUnit(),defs=model.classification?[['Accuracy','metricAccuracy','Proporción total clasificada correctamente.'],['Precision','metricPrecision','De los casos predichos como positivos, cuántos eran positivos.'],['Recall','metricRecall','De los positivos reales, cuántos detectó el modelo.'],['F1','metricF1','Equilibrio armónico entre Precision y Recall.']]:[['MAE','metricMAE',`Error absoluto promedio${unit?' en '+unit:''}.`],['RMSE','metricRMSE',`Error cuadrático típico${unit?' en '+unit:''}; penaliza más errores grandes.`],['R²','metricR2','Proporción de variabilidad de Y explicada respecto de usar solo la media.']];defs.forEach(([name,id,desc])=>{if(!$(id)?.checked)return;const key=name==='R²'?'R2':name,val=m[key],display=Number.isFinite(val)?(model.classification||name==='R²'?val.toFixed(3):`${val.toFixed(3)}${unit?' '+unit:''}`):'—',d=document.createElement('article');d.className='metric-card flip-mini';d.innerHTML=`<div class="mini-front"><span>${name}</span><b>${display}</b><p>${desc}</p></div><div class="mini-back"><span>¿QUÉ SIGNIFICA?</span><b>${display}</b><p>${metricInterpretation(name,val,model)}</p></div>`;d.onclick=()=>d.classList.toggle('is-flipped');box.appendChild(d)});if(model.classification&&m.tp!==undefined){const d=document.createElement('article');d.className='dynamic-card cm-wrap';d.innerHTML=`<div class="card-topline"><div><span class="kicker">MATRIZ DE CONFUSIÓN</span><h2>Real vs predicho</h2></div></div><div class="matrix-wrap"><table class="cm"><tr><th></th><th>Pred 0</th><th>Pred 1</th></tr><tr><th>Real 0</th><td class="ok">${m.tn}</td><td class="bad">${m.fp}</td></tr><tr><th>Real 1</th><td class="bad">${m.fn}</td><td class="ok">${m.tp}</td></tr></table></div>`;box.appendChild(d)}}
function metricInterpretation(name,val,model){const y=targetY()||'Y',unit=targetUnit();if(!Number.isFinite(val))return'Sin valor disponible.';if(name==='MAE')return`En promedio, la predicción se separa aproximadamente ${val.toFixed(3)}${unit?' '+unit:''} del valor real de ${y}.`;if(name==='RMSE')return`El error cuadrático es ${val.toFixed(3)}${unit?' '+unit:''}; errores grandes influyen más que en MAE.`;if(name==='R²')return val>=0?`El modelo explica aproximadamente ${(100*val).toFixed(1)}% de la variabilidad observada de ${y} frente al baseline de la media.`:`El modelo rinde peor que predecir la media en este conjunto.`;if(name==='Recall')return`Detecta aproximadamente ${(100*val).toFixed(1)}% de los positivos reales. Revisa el costo de los falsos negativos en tu contexto.`;if(name==='Precision')return`De los positivos que predice, aproximadamente ${(100*val).toFixed(1)}% son positivos reales.`;if(name==='Accuracy')return`Acierta aproximadamente ${(100*val).toFixed(1)}% del total; puede ser engañosa si las clases están desbalanceadas.`;return`F1 = ${val.toFixed(3)} resume el equilibrio entre Precision y Recall.`}
function interpretTrainingForUser(net){const box=$('resultMeaningBox');if(!box||!net?.trained)return;const t=net.trained,m=t.model,lastTr=t.trainHist.at(-1),lastVa=t.valHist.at(-1),evalData=prepareRows(State.split.test.length?State.split.test:State.split.val,m.stats).data,context=State.schema?.context||detectIndustrialContext(State.columns,targetY());let html=`<strong>${esc(context)}</strong><div class="decision-list">`;if(m.classification){const cm=classificationMetrics(m,evalData);html+=`<div class="decision-item"><strong>Recall ${(cm.Recall*100).toFixed(1)}%</strong><p>Indica qué fracción de los positivos reales detectó la red.</p></div><div class="decision-item"><strong>Precision ${(cm.Precision*100).toFixed(1)}%</strong><p>Indica cuántas alertas positivas fueron correctas.</p></div>`}else{const r=regressionMetrics(m,evalData),u=targetUnit();html+=`<div class="decision-item"><strong>MAE ${r.MAE.toFixed(3)}${u?' '+u:''}</strong><p>En promedio absoluto, esa es la distancia entre predicción y realidad.</p></div><div class="decision-item"><strong>RMSE ${r.RMSE.toFixed(3)}${u?' '+u:''}</strong><p>Los errores grandes pesan más en esta métrica.</p></div><div class="decision-item"><strong>R² ${r.R2.toFixed(3)}</strong><p>${metricInterpretation('R²',r.R2,m)}</p></div>`}const diag=interpretLearningCurve(t.trainHist,t.valHist);html+=`<div class="decision-item"><strong>Generalización</strong><p>${esc(diag)}</p></div><div class="decision-item"><strong>Siguiente revisión</strong><p>Compara estas métricas con el rango y costo real de error de ${esc(targetY()||'Y')}. El modelo apoya una decisión; no define por sí solo qué hacer.</p></div></div>`;box.innerHTML=html;updateResultBacks();updateDecisionPanel();markFlowState()}
function updateResultBacks(){const t=currentNet()?.trained;if(!t)return;const tr=t.trainHist,va=t.valHist,best=Math.min(...va),bi=va.indexOf(best)+1,lastTr=tr.at(-1),lastVa=va.at(-1);if($('lossCardBack'))$('lossCardBack').innerHTML=`<p><strong>Train final:</strong> ${fmtN(lastTr)}<br><strong>Validation final:</strong> ${fmtN(lastVa)}<br><strong>Mejor época:</strong> ${bi}<br><strong>Mejor val loss:</strong> ${fmtN(best)}<br><strong>Diferencia final:</strong> ${fmtN(lastVa-lastTr)}</p><p>${esc(interpretLearningCurve(tr,va))}</p>`;if(t.preds&&$('parityCardBack')){const e=t.preds.y.map((y,i)=>y-t.preds.p[i]),bias=mean(e),r=regressionMetrics(t.model,prepareRows(State.split.test.length?State.split.test:State.split.val,t.model.stats).data);$('parityCardBack').innerHTML=`<p><strong>MAE:</strong> ${fmtN(r.MAE)} ${esc(targetUnit())}<br><strong>RMSE:</strong> ${fmtN(r.RMSE)} ${esc(targetUnit())}<br><strong>R²:</strong> ${fmtN(r.R2)}<br><strong>Sesgo medio (real−pred):</strong> ${fmtN(bias)}</p><p>Observa si los puntos siguen la diagonal o si hay zonas donde el modelo falla sistemáticamente.</p>`}}

function analyzeCurrentModel(){const t=currentNet()?.trained;if(!t){notify('Entrena la red actual primero.','warning');return}const m=t.model;if(m.classification){notify('Para clasificación binaria usa ROC/PR y permutation importance se puede estudiar por separado.','info');renderThresholdLab();activateTab('lab75');return}const data=preparedForTrained(m,State.split.test.length?State.split.test:State.split.val);if(!data.length)return;const ys=data.map(o=>o.y*m.stats.ys+m.stats.ym),ps=data.map(o=>forward(m,o.x,false).y*m.stats.ys+m.stats.ym),res=ys.map((y,i)=>y-ps[i]);drawScatter($('residualCanvas'),ps.map((p,i)=>[p,res[i]]),true);drawHistogram($('residualHistCanvas'),res);const base=Math.sqrt(mean(res.map(v=>v*v))),rows=[];m.xs.forEach((name,j)=>{const perm=data.map(o=>({x:o.x.slice(),y:o.y})),vals=shuf(perm.map(o=>o.x[j]),seeded((+$('trainingSeed')?.value||42)+j+1));perm.forEach((o,i)=>o.x[j]=vals[i]);const rmse=Math.sqrt(mean(perm.map(o=>{const y=o.y*m.stats.ys+m.stats.ym,p=forward(m,o.x,false).y*m.stats.ys+m.stats.ym;return(y-p)**2})));rows.push({name,delta:rmse-base,rmse})});rows.sort((a,b)=>b.delta-a.delta);State.importance=rows;$('importanceTable').innerHTML='<table><thead><tr><th>Variable</th><th>Δ RMSE al permutar</th><th>RMSE permutado</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.delta.toFixed(4)}</td><td>${r.rmse.toFixed(4)}</td></tr>`).join('')+'</tbody></table>';if($('analysisSummary'))$('analysisSummary').innerHTML=`<strong>RMSE base:</strong> ${fmtN(base)} ${esc(targetUnit())}. Las primeras variables de la tabla son aquellas cuya información usa más el modelo. Esto no demuestra causalidad.`;updateDecisionPanel();notify('Análisis de residuos e importancia actualizado.','success')}
function updateDecisionPanel(){const s=State.schema||suggestSchema(State.rows,State.columns),ctx=s.context||'Analítica industrial general',imp=State.importance||[],top=imp.slice(0,4);if($('decisionImportance'))$('decisionImportance').innerHTML=top.length?top.map((x,i)=>`<div class="decision-item"><strong>${i+1}. ${esc(x.name)}</strong><p>Al permutarla, RMSE cambió ${fmtN(x.delta)}. Indica dependencia predictiva, no causalidad.</p></div>`).join(''):'<div class="decision-item"><strong>Aún sin ranking predictivo</strong><p>Entrena una regresión y ejecuta “Analizar modelo” para estimar permutation importance.</p></div>';const vars=top.map(x=>x.name),v1=vars[0]||State.columns.find(c=>State.roles[c]==='X')||'la variable principal',v2=vars[1]||'otra variable relevante',questions={
  'Confiabilidad y mantenimiento':[`¿Existe un umbral de ${v1} asociado a mayor probabilidad de falla?`,`¿Qué ocurre cuando ${v1} y ${v2} cambian simultáneamente?`,'¿La antigüedad, equipo o turno está confundiendo la relación?','¿Cómo cambia el costo de falsos negativos al mover el threshold?'],
  'Producción':[`¿En qué rango de ${v1} aumenta el tiempo de ciclo o baja productividad?`,`¿${v2} cambia por turno o línea?`,'¿La predicción podría alimentar scheduling o capacidad?','¿Hay zonas del proceso con errores residuales sistemáticos?'],
  'Transporte y logística':[`¿Cómo cambia el tiempo estimado al variar ${v1}?`,`¿Existe interacción entre ${v1} y ${v2}?`,'¿La predicción puede alimentar un VRP o un SLA?','¿El error es aceptable en rutas críticas?'],
  'Ingeniería económica':[`¿Cuánto cambia el resultado predicho ante variaciones de ${v1}?`,`¿Conviene llevar la predicción a un análisis de sensibilidad o Monte Carlo?`,'¿Qué costo tiene el error de predicción en VAN/TIR?','¿Hay variables que representan información disponible solo después de decidir?']
};const qs=questions[ctx]||[`¿Qué rango de ${v1} cambia más la predicción?`,`¿Cómo interactúan ${v1} y ${v2}?`,'¿Qué decisión operativa usaría esta predicción como parámetro?','¿Qué costo tiene un error del tamaño observado?'];if($('decisionQuestions'))$('decisionQuestions').innerHTML=qs.map(q=>`<div class="decision-item"><p>${esc(q)}</p></div>`).join('');if($('iciConnection'))$('iciConnection').innerHTML=[['Confiabilidad','Falla, MTBF, MTTR, RUL y disponibilidad.'],['Investigación Operativa','Predicciones como parámetros para PLEM, VRP, scheduling e inventario.'],['Ingeniería económica','Costo, demanda, riesgo, flujo y evaluación VAN/TIR posterior.'],['Producción','OEE, productividad, defectos y tiempos de ciclo.'],['Logística','Tiempo de viaje, retrasos, SLA y demanda.'],['Calidad','Defectos, scrap y variables de proceso.'],['Inventario','Demanda, quiebre y lead time.'],['RRHH','Ausentismo, productividad y dotación.']].map(([k,v])=>`<div class="ici-item"><strong>${k}</strong><span>${v}</span></div>`).join('')}

function renderComparison(){const box=$('comparisonTable');if(!box)return;let html='<table><thead><tr><th>Red</th><th>Arquitectura</th><th>Optimizador</th><th>Loss</th><th>Test loss</th><th>Parámetros</th><th>Complejidad</th><th>Generalización</th></tr></thead><tbody>';State.networks.forEach(n=>{const t=n.trained,s=t?.settings||{},sizes=[numericX().length,...n.hidden,1];let p=0;for(let i=0;i<sizes.length-1;i++)p+=sizes[i]*sizes[i+1]+sizes[i+1];const diag=t?interpretLearningCurve(t.trainHist,t.valHist):'Sin entrenar';html+=`<tr><td>${esc(n.name)}</td><td>${sizes.join('→')}</td><td>${esc(s.opt||'—')}</td><td>${esc(s.lossType||'—')}</td><td>${Number.isFinite(t?.testLoss)?t.testLoss.toFixed(6):'—'}</td><td>${p}</td><td>${p<100?'baja':p<1000?'media':'alta'}</td><td>${esc(diag)}</td></tr>`});html+='</tbody></table><p class="note">La tabla no declara una red “ganadora”. Compara error, complejidad, estabilidad y señales de overfitting según el objetivo industrial.</p>';box.innerHTML=html}
function simulateOptimizer(type,w0,g,lr,steps){let w=w0,v=0,s=0,m=0,t=0,u=0,arr=[w];for(let k=0;k<steps;k++){t++;if(type==='sgd')w-=lr*g;else if(type==='momentum'){v=.9*v-lr*g;w+=v}else if(type==='nesterov'){const old=v;v=.9*v-lr*g;w+=-.9*old+1.9*v}else if(type==='adagrad'){s+=g*g;w-=lr*g/(Math.sqrt(s)+1e-8)}else if(type==='rmsprop'){s=.9*s+.1*g*g;w-=lr*g/(Math.sqrt(s)+1e-8)}else if(type==='adam'||type==='adamw'){m=.9*m+.1*g;s=.999*s+.001*g*g;const mh=m/(1-.9**t),vh=s/(1-.999**t);if(type==='adamw')w*=1-lr*.01;w-=lr*mh/(Math.sqrt(vh)+1e-8)}else if(type==='adamax'){m=.9*m+.1*g;u=Math.max(.999*u,Math.abs(g));w-=lr/(1-.9**t)*m/(u+1e-8)}arr.push(w)}return arr}
function renderOptimizerVisibility(){const box=$('optimizerVisibility');if(!box)return;const types=['sgd','momentum','nesterov','adagrad','rmsprop','adam','adamw','adamax'];box.innerHTML=types.map(t=>`<label><input type="checkbox" data-opt-vis="${t}" ${State.optimizerVisibility[t]===false?'':'checked'}>${t.toUpperCase()}</label>`).join('');box.querySelectorAll('[data-opt-vis]').forEach(i=>i.onchange=()=>{State.optimizerVisibility[i.dataset.optVis]=i.checked;if(State.optimizerCompareData)drawOptimizerComparison(State.optimizerCompareData)})}
function runOptimizerComparison(){const w0=+$('compareWeight').value||1,g=+$('compareGradient').value||.3,lr=+$('compareLR').value||.1,steps=Math.max(1,+$('compareSteps').value||30),types=['sgd','momentum','nesterov','adagrad','rmsprop','adam','adamw','adamax'],data={};types.forEach(t=>data[t]=simulateOptimizer(t,w0,g,lr,steps));State.optimizerCompareData=data;renderOptimizerVisibility();drawOptimizerComparison(data);$('optimizerComparisonTable').innerHTML='<table><thead><tr><th>Optimizador</th><th>Peso inicial</th><th>Peso final</th><th>Cambio</th></tr></thead><tbody>'+types.map(t=>{const end=data[t].at(-1);return`<tr><td>${t.toUpperCase()}</td><td>${w0.toFixed(6)}</td><td>${end.toFixed(6)}</td><td>${(end-w0).toFixed(6)}</td></tr>`}).join('')+'</tbody></table>'}

function applyGeneralizationSuggestion(){const t=currentNet()?.trained;if(!t){$('useEarlyStopping').checked=true;$('useDropout').checked=true;$('dropoutRate').value=.2;notify('Aplicada una base conservadora: Early Stopping + Dropout 0.20.','success');return}const msg=interpretLearningCurve(t.trainHist,t.valHist);if(/overfitting/i.test(msg)){$('useEarlyStopping').checked=true;$('useDropout').checked=true;$('dropoutRate').value=.2;$('useL2').checked=true;$('l2Lambda').value=.001}else if(/underfitting/i.test(msg)){$('useDropout').checked=false;$('useL1').checked=false;$('useL2').checked=false;$('epochs').value=Math.min(2000,Math.round((+$('epochs').value||150)*1.4))}notify('Configuración sugerida aplicada. Vuelve a entrenar y compara Validation.','success')}
function markFlowState(){const hasData=State.rows.length>0,hasModel=State.networks.length>0,trained=!!currentNet()?.trained;document.querySelectorAll('[data-step-state="data"]').forEach(i=>i.className=hasData?'done':'');document.querySelectorAll('[data-step-state="model"]').forEach(i=>i.className=hasModel?(hasData?'ready':''):'');document.querySelectorAll('[data-step-state="train"]').forEach(i=>i.className=trained?'done':hasModel?'ready':'');document.querySelectorAll('[data-step-state="results"]').forEach(i=>i.className=trained?'ready':'')}

function contextExample(kind){const r=seeded(20260924),rows=[];for(let i=0;i<260;i++){if(kind==='Confiabilidad'){const vibr=1+r()*8,temp=45+r()*55,h=100+r()*7900,pres=2+r()*7,carga=.3+r()*.7,risk=-6+.52*vibr+.035*(temp-60)+.00025*h+.9*carga,fail=(1/(1+Math.exp(-risk))>r())?1:0;rows.push({equipo_id:`EQ-${1000+i}`,vibracion_mm_s:+vibr.toFixed(2),temperatura_C:+temp.toFixed(1),horas_operacion:+h.toFixed(0),presion_bar:+pres.toFixed(2),carga_motor:+carga.toFixed(2),falla_30_dias:fail})}else if(kind==='Producción'){const vel=40+r()*50,temp=120+r()*70,ciclo=90-vel*.45+Math.abs(temp-155)*.12+r()*7,def=(Math.abs(temp-155)>25||vel>82||r()<.08)?1:0;rows.push({linea_id:`L${1+i%4}`,velocidad:+vel.toFixed(1),temperatura:+temp.toFixed(1),tiempo_ciclo_min:+ciclo.toFixed(2),turno:['A','B','C'][i%3],defecto:def})}else if(kind==='Logística'){const d=5+r()*95,carga=200+r()*1400,cong=r(),par=Math.floor(r()*6),t=12+d*.72+carga*.006+cong*45+par*4+r()*8;rows.push({distancia_km:+d.toFixed(1),carga_kg:+carga.toFixed(0),congestion:+cong.toFixed(2),paradas:par,tiempo_viaje_min:+t.toFixed(1)})}else if(kind==='Ingeco'){const precio=7000+r()*3500,dem=500+r()*1300,costo=3500+r()*1600,inversion=2e6+r()*3e6,flujo=(precio-costo)*dem-inversion*.08+r()*2e5;rows.push({precio:+precio.toFixed(0),demanda:+dem.toFixed(0),costo_unitario:+costo.toFixed(0),inversion:+inversion.toFixed(0),flujo_neto:+flujo.toFixed(0)})}else if(kind==='IO'){const dem=20+r()*80,dist=5+r()*120,prio=1+Math.floor(r()*4),cap=40+r()*80,service=8+.25*dem+.18*dist-0.06*cap+prio*2+r()*5;rows.push({demanda:+dem.toFixed(1),distancia_km:+dist.toFixed(1),prioridad:prio,capacidad:+cap.toFixed(1),tiempo_servicio_min:+service.toFixed(1)})}else if(kind==='Calidad'){const temp=160+r()*45,pres=3+r()*5,vel=20+r()*40,hum=20+r()*50,def=(Math.abs(temp-180)>14||pres<3.8||hum>58||r()<.05)?1:0;rows.push({temperatura:+temp.toFixed(1),presion_bar:+pres.toFixed(2),velocidad:+vel.toFixed(1),humedad:+hum.toFixed(1),defecto:def})}else{const dem=20+r()*80,lead=1+r()*9,stock=30+r()*160,est=['baja','media','alta'][i%3],q=(dem*lead/5>stock||r()<.06)?1:0;rows.push({sku_id:`SKU-${i+1}`,demanda_diaria:+dem.toFixed(1),lead_time_dias:+lead.toFixed(1),stock_actual:+stock.toFixed(0),temporada:est,quiebre:q})}}return rows}
function readCSV(file){if(!file)return;const fr=new FileReader();fr.onload=()=>{const lines=String(fr.result).replace(/^\uFEFF/,'').replace(/\r/g,'').split('\n').filter(x=>x.trim());if(lines.length<2){notify('El CSV necesita encabezado y al menos una fila.','warning');return}const d=[',',';','\t','|'].map(x=>[x,splitLine(lines[0],x).length]).sort((a,b)=>b[1]-a[1])[0][0],heads=splitLine(lines[0],d).map(x=>x.trim()).filter(Boolean);if(new Set(heads).size!==heads.length){notify('Hay encabezados duplicados. Renómbralos antes de importar.','warning');return}const rows=lines.slice(1).map(line=>{const v=splitLine(line,d),o={};heads.forEach((h,i)=>{const s=(v[i]??'').trim(),clean=s.replace(/,/g,'.'),n=Number(clean);o[h]=Number.isFinite(n)&&s!==''&&!/^0\d+/.test(s)?n:s});return o});loadData(rows);$('homeDatasetName').textContent=file.name;$('csvInput').value='';activateTab('home');notify(`CSV analizado: ${rows.length} filas y ${heads.length} columnas.`,'success')};fr.readAsText(file)}
