/* Industrial Neural Lab v9.3 · UCN course integration
   Offline, no external dependencies. Adds full activation catalogue,
   extended classification metrics and an educational CNN convolution lab. */
const V93={version:'9.3',cnn:{matrix:null,feature:null,pool:null}};

const ACTIVATION_OPTIONS_V93=[
  ['sigmoid','Sigmoid'],['tanh','Tanh'],['relu','ReLU'],['leaky','Leaky ReLU'],['elu','ELU'],
  ['softplus','Softplus'],['swish','Swish'],['gelu','GELU'],['linear','Lineal'],['softsign','Softsign'],
  ['hard_sigmoid','Hard Sigmoid'],['hard_tanh','Hard Tanh'],['mish','Mish']
];
const ACTIVATION_DEFS_V93={
  sigmoid:{name:'Sigmoid',formula:'<span>σ(x) = </span><span class="frac"><span>1</span><span>1 + e<sup>−x</sup></span></span>',plain:'σ(x) = 1 / (1 + e^(−x))',range:'(0, 1)',gradient:'Máx. 0,25; se satura',short:'Probabilidades / compuertas',desc:'Comprime cualquier valor real entre 0 y 1. Es una función clásica cuando la salida se interpreta como probabilidad.',uses:'Salida de clasificación binaria y compuertas de LSTM/GRU. En capas ocultas profundas suele evitarse porque puede saturar el gradiente.',adv:'Tiene interpretación probabilística clara y es suave y derivable.',risk:'Para |x| grande el gradiente se acerca a cero; puede producir vanishing gradients.',industrial:'Probabilidad de falla de un equipo dentro de los próximos 30 días.'},
  tanh:{name:'Tanh',formula:'<span>tanh(x) = </span><span class="frac"><span>e<sup>x</sup> − e<sup>−x</sup></span><span>e<sup>x</sup> + e<sup>−x</sup></span></span>',plain:'tanh(x) = (e^x − e^(−x)) / (e^x + e^(−x))',range:'(−1, 1)',gradient:'Máx. 1 en x=0',short:'Estados centrados en 0',desc:'Transformación sigmoidal centrada en cero. Permite activaciones negativas y positivas.',uses:'Capas ocultas pequeñas, estados recurrentes y problemas donde una representación centrada puede ayudar.',adv:'Está centrada en cero y su gradiente alrededor del origen es mayor que el de Sigmoid.',risk:'También se satura en valores extremos y puede sufrir vanishing gradients.',industrial:'Modelar un estado interno de demanda o presión normalizada con desviaciones positivas y negativas.'},
  relu:{name:'ReLU',formula:'<span>ReLU(x) = max(0, x)</span>',plain:'ReLU(x) = max(0, x)',range:'[0, ∞)',gradient:'0 o 1',short:'Capas ocultas densas',desc:'Deja pasar los valores positivos y lleva los negativos a cero.',uses:'Es una de las opciones base para MLP y CNN por su simplicidad y buen flujo de gradiente en la región positiva.',adv:'Muy barata de calcular y no se satura para x positivo.',risk:'Una neurona puede quedar “muerta” si permanece en la zona negativa y deja de recibir gradiente.',industrial:'Capas ocultas para predecir tiempo de ciclo, costos, demanda o riesgo operacional.'},
  leaky:{name:'Leaky ReLU',formula:'<span>f(x) = x si x ≥ 0; αx si x &lt; 0</span>',plain:'LeakyReLU(x) = max(x, αx), α≈0,01',range:'(−∞, ∞)',gradient:'1 o α',short:'Evitar ReLU muertas',desc:'Variante de ReLU que conserva una pequeña pendiente cuando x es negativo.',uses:'Capas ocultas cuando se observan muchas activaciones ReLU permanentemente en cero.',adv:'Reduce el riesgo de neuronas muertas manteniendo gradiente en la zona negativa.',risk:'α es un hiperparámetro y una pendiente negativa no garantiza mejor generalización.',industrial:'Redes para señales de vibración o variables estandarizadas con valores negativos frecuentes.'},
  elu:{name:'ELU',formula:'<span>ELU(x) = x si x&gt;0; α(e<sup>x</sup>−1) si x≤0</span>',plain:'ELU(x)=x si x>0; α(e^x−1) si x≤0',range:'(−α, ∞)',gradient:'Suave en zona negativa',short:'Capas profundas',desc:'Mantiene la región positiva lineal y usa una curva exponencial suave en la zona negativa.',uses:'Alternativa a ReLU cuando se desea una activación negativa suave y continua.',adv:'Puede producir activaciones más cercanas a cero y evita el corte brusco negativo de ReLU.',risk:'Es más costosa que ReLU y puede saturar en la cola negativa.',industrial:'Modelos de proceso con variables normalizadas donde desviaciones negativas contienen información.'},
  softplus:{name:'Softplus',formula:'<span>Softplus(x) = ln(1 + e<sup>x</sup>)</span>',plain:'Softplus(x) = ln(1 + e^x)',range:'(0, ∞)',gradient:'σ(x)',short:'ReLU suave / salida positiva',desc:'Aproximación suave de ReLU. Nunca produce valores negativos y no tiene una esquina en cero.',uses:'Capas ocultas o salidas que deben permanecer positivas; también sirve para enseñar la relación con Sigmoid porque su derivada es σ(x).',adv:'Es suave en todo el dominio y conserva gradiente continuo.',risk:'Puede ser más lenta que ReLU y para valores muy negativos el gradiente se vuelve pequeño.',industrial:'Parámetros internos asociados a tiempos, tasas o intensidades que conceptualmente no son negativas.'},
  swish:{name:'Swish',formula:'<span>Swish(x) = x · σ(x)</span>',plain:'Swish(x) = x·σ(x)',range:'≈ [−0,278, ∞)',gradient:'Suave; no monotónica',short:'Redes profundas',desc:'Multiplica la entrada por una compuerta Sigmoid. Es suave y permite pequeños valores negativos.',uses:'Capas ocultas profundas; puede sustituir ReLU cuando se quiere experimentar con una activación suave auto-regulada.',adv:'No corta completamente la zona negativa y mantiene una transición suave.',risk:'Es más costosa y no siempre mejora una MLP pequeña; debe validarse con datos.',industrial:'Comparar arquitecturas para mantenimiento predictivo con muchas variables continuas estandarizadas.'},
  gelu:{name:'GELU',formula:'<span>GELU(x) ≈ ½x[1 + tanh(√(2/π)(x + 0,044715x<sup>3</sup>))]</span>',plain:'GELU(x) ≈ 0,5x[1+tanh(√(2/π)(x+0,044715x³))]',range:'≈ [−0,17, ∞)',gradient:'Suave; pondera por magnitud',short:'Modelos profundos modernos',desc:'Pondera suavemente cada entrada según su magnitud en lugar de aplicar un corte rígido.',uses:'Muy usada en Transformers y útil como experimento en redes profundas densas.',adv:'Transición suave y gradiente continuo; evita el umbral duro de ReLU.',risk:'Mayor costo computacional y poca justificación para elegirla sin comparación de validación.',industrial:'Laboratorios avanzados donde se comparan activaciones manteniendo fija la arquitectura y el split.'},
  linear:{name:'Lineal',formula:'<span>f(x) = x</span>',plain:'f(x) = x',range:'(−∞, ∞)',gradient:'1 constante',short:'Salida de regresión',desc:'No modifica la suma ponderada de la neurona.',uses:'Principalmente como activación de salida en regresión: costo, tiempo, demanda o cualquier Y continua sin cota explícita.',adv:'No limita el rango de la predicción.',risk:'Si todas las capas fueran lineales, varias capas colapsan matemáticamente a una sola transformación lineal.',industrial:'Predicción de tiempo de viaje, costo unitario o demanda continua.'},
  softsign:{name:'Softsign',formula:'<span>Softsign(x) = </span><span class="frac"><span>x</span><span>1 + |x|</span></span>',plain:'Softsign(x) = x / (1 + |x|)',range:'(−1, 1)',gradient:'1/(1+|x|)²',short:'Alternativa suave a tanh',desc:'Comprime los valores hacia −1 y 1 mediante una función racional.',uses:'Capas ocultas experimentales cuando se busca una saturación más lenta que tanh.',adv:'Las colas se acercan a los límites de forma más lenta que tanh.',risk:'Sigue saturándose y suele tener menos soporte empírico que ReLU/GELU en arquitecturas modernas.',industrial:'Comparación académica de activaciones sobre una misma red de producción o calidad.'},
  hard_sigmoid:{name:'Hard Sigmoid',formula:'<span>f(x) = clip(x/6 + 1/2, 0, 1)</span>',plain:'HardSigmoid(x) = clip(x/6 + 0,5, 0, 1)',range:'[0, 1]',gradient:'1/6 en (−3,3); 0 fuera',short:'Compuertas eficientes',desc:'Aproximación lineal por tramos de Sigmoid.',uses:'Compuertas o modelos donde el costo computacional importa más que una transición perfectamente suave.',adv:'Más barata que Sigmoid y mantiene interpretación acotada 0–1.',risk:'Fuera de la zona lineal el gradiente es exactamente cero.',industrial:'Prototipos ligeros en dispositivos de borde para activar/desactivar una señal probabilística.'},
  hard_tanh:{name:'Hard Tanh',formula:'<span>f(x) = clip(x, −1, 1)</span>',plain:'HardTanh(x) = clip(x, −1, 1)',range:'[−1, 1]',gradient:'1 en (−1,1); 0 fuera',short:'Estados acotados eficientes',desc:'Versión lineal por tramos de tanh.',uses:'Redes compactas o experimentos donde se desea limitar activaciones entre −1 y 1 con cálculo muy simple.',adv:'Cálculo barato y rango perfectamente acotado.',risk:'Gradiente nulo fuera de [−1,1], lo que puede congelar unidades saturadas.',industrial:'Estado interno acotado para indicadores normalizados de operación.'},
  mish:{name:'Mish',formula:'<span>Mish(x) = x · tanh(ln(1 + e<sup>x</sup>))</span>',plain:'Mish(x)=x·tanh(softplus(x))',range:'≈ [−0,31, ∞)',gradient:'Suave; no monotónica',short:'Redes profundas experimentales',desc:'Activación suave y no monotónica que combina Softplus y tanh.',uses:'Capas ocultas profundas cuando se desea comparar alternativas modernas a ReLU/Swish.',adv:'Suavidad completa y pequeño flujo negativo.',risk:'Mayor costo de cálculo y no existe garantía de mejorar el desempeño en datasets tabulares pequeños.',industrial:'Benchmark de arquitectura para un problema de confiabilidad o calidad con suficientes observaciones.'}
};

Object.assign(InfoLibrary,{
  activation:{title:'Funciones de activación',formula:'a = f(z)',text:'La función de activación transforma la suma ponderada z y permite que una red represente relaciones no lineales.',use:'Define cómo una neurona deja pasar, recorta o comprime la información hacia la capa siguiente.',variables:{'z':'suma ponderada Σwx+b','f(z)':'transformación aplicada','a':'salida de la neurona','f′(z)':'pendiente usada por backpropagation'},example:'Una activación puede transformar la señal combinada de vibración, temperatura y carga antes de pasarla a la siguiente capa.',error:'Elegir una activación solo por moda. Debe ser compatible con la capa y validarse con Train/Validation.'},
  cnn:{title:'Red neuronal convolucional (CNN)',formula:'(I ∗ K)(x,y) = ΣᵢΣⱼ I(x+i,y+j)K(i,j)',text:'Una CNN aprende filtros que recorren una imagen para detectar patrones locales y construir mapas de activación.',use:'Clasificación, detección o inspección visual de defectos, objetos, superficies y componentes.',variables:{'I':'imagen de entrada','K':'kernel o filtro','∗':'operación de convolución','feature map':'resultado de aplicar el kernel','pooling':'reducción espacial'},example:'Inspección visual de grietas, corrosión, EPP o defectos superficiales en una línea de producción.',error:'Confundir una convolución manual con una CNN entrenada. En entrenamiento los kernels se aprenden por backpropagation.'}
});
if(typeof V9!=='undefined')V9.viewTitles.cnn=['CNN · VISIÓN ARTIFICIAL','Convolución, filtros y mapas de activación'];

function activationOptionsHTMLV93(selected){return ACTIVATION_OPTIONS_V93.map(([v,n])=>`<option value="${v}" ${v===selected?'selected':''}>${n}</option>`).join('')}
function patchLayerActivationSelectsV93(){
  document.querySelectorAll('[data-layer-act]').forEach(sel=>{
    const current=sel.value||'relu';sel.innerHTML=activationOptionsHTMLV93(current);sel.value=current;
    const idx=sel.dataset.layerAct,host=sel.closest('.layer-row')?.querySelector('.layer-options')?.parentElement;
    let hint=host?.querySelector(`[data-layer-act-hint="${idx}"]`);
    if(host&&!hint){hint=document.createElement('button');hint.type='button';hint.className='layer-activation-hint';hint.dataset.layerActHint=idx;host.appendChild(hint)}
    const update=()=>{const d=ACTIVATION_DEFS_V93[sel.value]||ACTIVATION_DEFS_V93.relu;if(hint)hint.innerHTML=`<span>${esc(d.name)}</span><small>${esc(d.plain)} · ${esc(d.range)}</small><b aria-hidden="true">i</b>`};
    update();
    if(sel.dataset.v93ActivationPatched!=='1'){
      const prior=sel.onchange;sel.onchange=e=>{if(prior)prior.call(sel,e);update()};sel.dataset.v93ActivationPatched='1';
      hint?.addEventListener('click',()=>{const ex=$('activationExplorerSelect');if(ex){ex.value=sel.value;renderActivationExplorerV93()}openActivationModalV93()});
    }
  });
}
const _v93RenderCurrentNetwork=window.renderCurrentNetwork;
window.renderCurrentNetwork=function(){_v93RenderCurrentNetwork();patchLayerActivationSelectsV93();renderActivationExplorerV93()};

function formulaRichV93(key){const d=ACTIVATION_DEFS_V93[key];return `<div class="formula-rich">${d?.formula||''}</div>`}
function renderActivationExplorerV93(){
  const select=$('activationExplorerSelect');if(!select)return;const key=select.value||'sigmoid',d=ACTIVATION_DEFS_V93[key];if(!d)return;
  $('activationFormulaRich').innerHTML=formulaRichV93(key);$('activationRange').textContent=d.range;$('activationGradient').textContent=d.gradient;$('activationUseShort').textContent=d.short;
  $('activationDescription').textContent=d.desc;$('activationUses').textContent=d.uses;$('activationAdvantage').textContent=d.adv;$('activationRisk').textContent=d.risk;$('activationIndustrial').textContent=d.industrial;drawActivationChartV93(key)
}
function drawActivationChartV93(key){
  const cv=$('activationCanvas');if(!cv)return;const c=cv.getContext('2d'),W=cv.width,H=cv.height,pad={l:62,r:28,t:28,b:48};c.clearRect(0,0,W,H);
  const get=(name,fallback)=>getComputedStyle(document.documentElement).getPropertyValue(name).trim()||fallback,grid=get('--line','#d9dde2'),ink=get('--ink','#171b20'),muted=get('--muted','#727b84'),main=get('--ucn-cyan','#687a84'),der=get('--ucn-orange','#8c8170');
  const xs=Array.from({length:241},(_,i)=>-6+12*i/240),ys=xs.map(x=>activation(x,key)),ds=xs.map((x,i)=>dactivation(ys[i],key,x));let ymin=Math.min(...ys,...ds,0),ymax=Math.max(...ys,...ds,0);
  if(key==='linear'){ymin=-6;ymax=6}else{ymin=Math.max(-3,Math.floor(ymin-.3));ymax=Math.min(7,Math.ceil(ymax+.3));if(ymax-ymin<2){ymax+=1;ymin-=1}}
  const sx=x=>pad.l+(x+6)/12*(W-pad.l-pad.r),sy=y=>H-pad.b-(y-ymin)/(ymax-ymin)*(H-pad.t-pad.b);
  c.strokeStyle=grid;c.lineWidth=1;for(let i=0;i<=6;i++){const x=-6+i*2;c.beginPath();c.moveTo(sx(x),pad.t);c.lineTo(sx(x),H-pad.b);c.stroke()}for(let i=0;i<=6;i++){const y=ymin+(ymax-ymin)*i/6;c.beginPath();c.moveTo(pad.l,sy(y));c.lineTo(W-pad.r,sy(y));c.stroke()}
  c.strokeStyle=ink;c.lineWidth=1.4;c.beginPath();c.moveTo(pad.l,sy(0));c.lineTo(W-pad.r,sy(0));c.stroke();c.beginPath();c.moveTo(sx(0),pad.t);c.lineTo(sx(0),H-pad.b);c.stroke();
  const curve=(vals,col,w=3)=>{c.strokeStyle=col;c.lineWidth=w;c.beginPath();vals.forEach((y,i)=>{const X=sx(xs[i]),Y=sy(Math.max(ymin,Math.min(ymax,y)));i?c.lineTo(X,Y):c.moveTo(X,Y)});c.stroke()};curve(ys,main,3.2);curve(ds,der,2.4);
  c.fillStyle=muted;c.font='18px Segoe UI';c.textAlign='center';[-6,-4,-2,0,2,4,6].forEach(x=>c.fillText(String(x),sx(x),H-14));c.textAlign='right';for(let i=0;i<=4;i++){const y=ymin+(ymax-ymin)*i/4;c.fillText(y.toFixed(1),pad.l-9,sy(y)+5)}
}
function openActivationModalV93(){const key=$('activationExplorerSelect')?.value||'sigmoid',d=ACTIVATION_DEFS_V93[key],modal=$('infoModal');if(!d||!modal)return;$('infoCategory').textContent='FUNCIÓN DE ACTIVACIÓN';$('infoTitle').textContent=d.name;$('infoFormula').innerHTML=formulaRichV93(key);$('infoText').textContent=d.desc;$('infoUse').textContent=d.uses;$('infoVariables').innerHTML=`<div class="symbol-row"><b>x / z</b><span>entrada o suma ponderada</span></div><div class="symbol-row"><b>f(x)</b><span>activación resultante</span></div><div class="symbol-row"><b>f′(x)</b><span>pendiente usada durante backpropagation</span></div><div class="symbol-row"><b>Rango</b><span>${d.range}</span></div>`;$('infoExample').textContent=d.industrial;$('infoError').textContent=d.risk;modal.classList.add('open')}
function applyActivationToNetworkV93(){const key=$('activationExplorerSelect')?.value||'relu',n=currentNet();if(!n)return;n.hiddenActivation=key;n.layerSettings=n.hidden.map((_,i)=>({...{dropout:0,batchNorm:false,bias:true},...(n.layerSettings?.[i]||{}),activation:key}));const heLike=['relu','leaky','elu','softplus','swish','gelu','mish'];n.initMethod=heLike.includes(key)?'he':'xavier';if($('hiddenActivation'))$('hiddenActivation').value=key;if($('initMethod'))$('initMethod').value=n.initMethod;renderCurrentNetwork();notify(`${ACTIVATION_DEFS_V93[key].name} aplicada a todas las capas ocultas. Inicialización ${n.initMethod.toUpperCase()}.`,'success')}

/* Métricas de clasificación ampliadas: conserva el motor y agrega las métricas del curso. */
window.classificationMetrics=function(model,data){let tp=0,tn=0,fp=0,fn=0;data.forEach(o=>{const p=forward(model,o.x,false).y>=.5?1:0,y=o.y;if(p===1&&y===1)tp++;else if(p===0&&y===0)tn++;else if(p===1&&y===0)fp++;else fn++});const N=Math.max(1,tp+tn+fp+fn),Accuracy=(tp+tn)/N,Precision=tp/Math.max(1,tp+fp),Recall=tp/Math.max(1,tp+fn),Specificity=tn/Math.max(1,tn+fp),F1=(Precision+Recall)?2*Precision*Recall/(Precision+Recall):0,BalancedAccuracy=(Recall+Specificity)/2;return{Accuracy,Precision,Recall,F1,Specificity,BalancedAccuracy,tp,tn,fp,fn}}
if(typeof mcMetricsV91==='function'){
  window.mcMetricsV91=function(m,data){const k=m.stats.classes.length,cm=Array.from({length:k},()=>Array(k).fill(0));let correct=0;data.forEach(o=>{const q=forward(m,o.x,false),p=q.predClass;cm[o.y][p]++;if(p===o.y)correct++});const total=Math.max(1,data.length),per=Array.from({length:k},(_,c)=>{const tp=cm[c][c],support=cm[c].reduce((s,v)=>s+v,0),fp=cm.reduce((s,r,i)=>s+(i===c?0:r[c]),0),fn=support-tp,tn=total-tp-fp-fn,precision=tp/Math.max(1,tp+fp),recall=tp/Math.max(1,tp+fn),specificity=tn/Math.max(1,tn+fp),f1=(precision+recall)?2*precision*recall/(precision+recall):0;return{precision,recall,specificity,f1,support}}),weighted=field=>per.reduce((s,x)=>s+x[field]*x.support,0)/total,macro=field=>mean(per.map(x=>x[field]));const Accuracy=correct/total;return{Accuracy,Precision:macro('precision'),Recall:macro('recall'),F1:macro('f1'),Specificity:macro('specificity'),BalancedAccuracy:macro('recall'),PrecisionWeighted:weighted('precision'),RecallWeighted:weighted('recall'),F1Weighted:weighted('f1'),PrecisionMicro:Accuracy,RecallMicro:Accuracy,F1Micro:Accuracy,cm,per}}
}
const _v93RenderEval=window.renderEvaluationMetrics;
window.renderEvaluationMetrics=function(model,data){
  if(!model?.classification)return _v93RenderEval(model,data);const box=$('evaluationMetrics');if(!box)return;
  if(model.multiclass){const m=mcMetricsV91(model,data),defs=[['Accuracy',m.Accuracy,'aciertos / total','Desempeño global. Puede ocultar clases pequeñas.'],['Precision macro',m.Precision,'promedio simple por clase','Cada clase pesa lo mismo.'],['Recall macro',m.Recall,'promedio simple por clase','Mide recuperación equitativa entre clases.'],['F1 macro',m.F1,'media de F1 por clase','Equilibra Precision y Recall dando igual peso a cada clase.'],['F1 weighted',m.F1Weighted,'Σ soporteₖ·F1ₖ / N','Pondera las clases según su frecuencia real.'],['F1 micro',m.F1Micro,'TP global / decisiones globales','Agrega todas las decisiones antes de calcular la métrica.']];box.innerHTML=defs.map(([n,v,f,t])=>metricCardHTMLV91(n,v,f,t,'')).join('');box.querySelectorAll('.metric-card-v91').forEach(c=>c.onclick=()=>c.classList.toggle('is-flipped'));const wrap=document.createElement('div');wrap.className='matrix-wrap';wrap.style.gridColumn='1/-1';wrap.innerHTML='<table><thead><tr><th>Real \\ Pred</th>'+model.stats.classes.map(c=>`<th>${esc(String(c).slice(0,16))}</th>`).join('')+'</tr></thead><tbody>'+m.cm.map((r,i)=>`<tr><th>${esc(String(model.stats.classes[i]).slice(0,16))}</th>${r.map((v,j)=>`<td class="${i===j?'ok':'bad'}">${v}</td>`).join('')}</tr>`).join('')+'</tbody></table>';box.appendChild(wrap);const by=document.createElement('div');by.className='table-wrap';by.style.gridColumn='1/-1';by.innerHTML='<table><thead><tr><th>Clase</th><th>Support</th><th>Precision</th><th>Recall</th><th>F1</th><th>Specificity</th></tr></thead><tbody>'+m.per.map((x,i)=>`<tr><td>${esc(String(model.stats.classes[i]))}</td><td>${x.support}</td><td>${fmtN(x.precision)}</td><td>${fmtN(x.recall)}</td><td>${fmtN(x.f1)}</td><td>${fmtN(x.specificity)}</td></tr>`).join('')+'</tbody></table>';box.appendChild(by);return
  }
  const m=classificationMetrics(model,data),enabled={Accuracy:$('metricAccuracy')?.checked!==false,Precision:$('metricPrecision')?.checked!==false,Recall:$('metricRecall')?.checked!==false,F1:$('metricF1')?.checked!==false,Specificity:$('metricSpecificity')?.checked!==false,'Balanced Accuracy':$('metricBalancedAccuracy')?.checked!==false},defs=[['Accuracy',m.Accuracy,'(TP+TN)/N',`Acierta aproximadamente ${(100*m.Accuracy).toFixed(1)}% del total.`],['Precision',m.Precision,'TP/(TP+FP)',`De las alertas positivas, ${(100*m.Precision).toFixed(1)}% fueron positivas reales.`],['Recall',m.Recall,'TP/(TP+FN)',`Detecta ${(100*m.Recall).toFixed(1)}% de los positivos reales.`],['F1',m.F1,'2·P·R/(P+R)','Equilibra Precision y Recall.'],['Specificity',m.Specificity,'TN/(TN+FP)',`Reconoce ${(100*m.Specificity).toFixed(1)}% de los negativos reales.`],['Balanced Accuracy',m.BalancedAccuracy,'(Recall+Specificity)/2','Promedia desempeño sobre positivos y negativos; es útil cuando hay desbalance.']];box.innerHTML=defs.filter(d=>enabled[d[0]]).map(([n,v,f,t])=>metricCardHTMLV91(n,v,f,t,'')).join('')+`<div class="matrix-wrap" style="grid-column:1/-1"><table class="cm"><tr><th></th><th>Pred 0</th><th>Pred 1</th></tr><tr><th>Real 0</th><td class="ok">${m.tn}</td><td class="bad">${m.fp}</td></tr><tr><th>Real 1</th><td class="bad">${m.fn}</td><td class="ok">${m.tp}</td></tr></table></div>`;box.querySelectorAll('.metric-card-v91').forEach(c=>c.onclick=()=>c.classList.toggle('is-flipped'))
};

/* CNN: convolución/pooling reales en el navegador; entrenamiento no simulado. */
const CNN_KERNELS_V93={
 edge:[[1,0,-1],[1,0,-1],[1,0,-1]],sobel:[[-1,-2,-1],[0,0,0],[1,2,1]],sharpen:[[0,-1,0],[-1,5,-1],[0,-1,0]],blur:[[1/9,1/9,1/9],[1/9,1/9,1/9],[1/9,1/9,1/9]],laplace:[[0,1,0],[1,-4,1],[0,1,0]]
};
function demoImageV93(){const n=28,a=Array.from({length:n},(_,y)=>Array.from({length:n},(_,x)=>{let v=.28+.18*Math.sin(x*.42)+.12*Math.cos(y*.55);const scratch=Math.abs(y-(.55*x+5))<1.1||Math.abs(y-(-.35*x+25))<.7;if(scratch)v=.95;const pit=(x-19)**2+(y-8)**2<10;if(pit)v=.04;return Math.max(0,Math.min(1,v))}));V93.cnn.matrix=a;drawCNNMatrixV93($('cnnInputCanvas'),a,'gray');updateCNNInputStatsV93();renderKernelV93()}
function drawCNNMatrixV93(cv,matrix,mode='heat'){if(!cv||!matrix?.length)return;const ctx=cv.getContext('2d'),h=matrix.length,w=matrix[0].length,img=ctx.createImageData(w,h),flat=matrix.flat(),mn=Math.min(...flat),mx=Math.max(...flat),span=mx-mn||1;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,t=Math.max(0,Math.min(1,(matrix[y][x]-mn)/span));let r,g,b;if(mode==='gray')r=g=b=Math.round(t*255);else{r=Math.round(18+225*Math.max(0,(t-.55)/.45));g=Math.round(50+150*t);b=Math.round(90+130*(1-t))}img.data[i]=r;img.data[i+1]=g;img.data[i+2]=b;img.data[i+3]=255}const tmp=document.createElement('canvas');tmp.width=w;tmp.height=h;tmp.getContext('2d').putImageData(img,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,cv.width,cv.height);ctx.drawImage(tmp,0,0,cv.width,cv.height)}
function updateCNNInputStatsV93(){const a=V93.cnn.matrix?.flat()||[];$('cnnInputShape').textContent=V93.cnn.matrix?`${V93.cnn.matrix.length}×${V93.cnn.matrix[0].length}×1`:'—';$('cnnInputMin').textContent=a.length?Math.min(...a).toFixed(3):'—';$('cnnInputMax').textContent=a.length?Math.max(...a).toFixed(3):'—'}
function renderKernelV93(){const key=$('cnnKernelSelect')?.value||'edge',k=CNN_KERNELS_V93[key],box=$('cnnKernelGrid');if(box)box.innerHTML=k.flat().map(v=>`<span>${Math.abs(v)<1e-12?'0':Number(v.toFixed(3))}</span>`).join('')}
function convolveV93(input,kernel,stride=1,padding='same'){const ih=input.length,iw=input[0].length,kh=kernel.length,kw=kernel[0].length,pad=padding==='same'?Math.floor(kh/2):0,oh=Math.floor((ih+2*pad-kh)/stride)+1,ow=Math.floor((iw+2*pad-kw)/stride)+1,out=Array.from({length:oh},()=>Array(ow).fill(0));for(let oy=0;oy<oh;oy++)for(let ox=0;ox<ow;ox++){let s=0;for(let ky=0;ky<kh;ky++)for(let kx=0;kx<kw;kx++){const iy=oy*stride+ky-pad,ix=ox*stride+kx-pad;if(iy>=0&&iy<ih&&ix>=0&&ix<iw)s+=input[iy][ix]*kernel[ky][kx]}out[oy][ox]=Math.max(0,s)}return out}
function maxPoolV93(input,size=2,stride=2){const ih=input.length,iw=input[0].length,oh=Math.max(1,Math.floor((ih-size)/stride)+1),ow=Math.max(1,Math.floor((iw-size)/stride)+1),out=Array.from({length:oh},()=>Array(ow).fill(0));for(let oy=0;oy<oh;oy++)for(let ox=0;ox<ow;ox++){let m=-Infinity;for(let y=0;y<size;y++)for(let x=0;x<size;x++)m=Math.max(m,input[oy*stride+y]?.[ox*stride+x]??-Infinity);out[oy][ox]=Number.isFinite(m)?m:0}return out}
function runCNNV93(){if(!V93.cnn.matrix)demoImageV93();const key=$('cnnKernelSelect')?.value||'edge',stride=+$('cnnStride')?.value||1,padding=$('cnnPadding')?.value||'same',k=CNN_KERNELS_V93[key],feat=convolveV93(V93.cnn.matrix,k,stride,padding),pool=maxPoolV93(feat,2,2);V93.cnn.feature=feat;V93.cnn.pool=pool;drawCNNMatrixV93($('cnnFeatureCanvas'),feat,'heat');drawCNNMatrixV93($('cnnPoolCanvas'),pool,'heat');$('cnnFeatureShape').textContent=`${feat.length}×${feat[0].length}`;$('cnnPoolShape').textContent=`${pool.length}×${pool[0].length}`;$('cnnOps').textContent=(feat.length*feat[0].length*9).toLocaleString('es-CL');const label={edge:'bordes verticales',sobel:'cambios horizontales',sharpen:'detalles locales',blur:'estructura suavizada',laplace:'cambios bruscos en varias direcciones'}[key];const maxAct=Math.max(...feat.flat()),active=feat.flat().filter(v=>v>maxAct*.55).length;$('cnnInterpretation').innerHTML=`<strong>Filtro: ${label}</strong><p>Después de ReLU, ${active} de ${feat.length*feat[0].length} posiciones superan 55% de la activación máxima. Las regiones claras indican dónde este kernel responde con mayor intensidad.</p><p class="note">En una CNN entrenada, estos valores del kernel no se eligen manualmente: se aprenden durante backpropagation.</p>`}
function loadCNNImageV93(file){if(!file)return;const fr=new FileReader();fr.onload=()=>{const img=new Image();img.onload=()=>{const off=document.createElement('canvas');off.width=28;off.height=28;const c=off.getContext('2d');c.fillStyle='#000';c.fillRect(0,0,28,28);const scale=Math.max(28/img.width,28/img.height),w=img.width*scale,h=img.height*scale;c.drawImage(img,(28-w)/2,(28-h)/2,w,h);const px=c.getImageData(0,0,28,28).data,V=Array.from({length:28},()=>Array(28).fill(0));for(let y=0;y<28;y++)for(let x=0;x<28;x++){const i=(y*28+x)*4;V[y][x]=(.2126*px[i]+.7152*px[i+1]+.0722*px[i+2])/255}V93.cnn.matrix=V;drawCNNMatrixV93($('cnnInputCanvas'),V,'gray');updateCNNInputStatsV93();runCNNV93();notify('Imagen procesada localmente a 28×28 en escala de grises.','success')};img.src=fr.result};fr.readAsDataURL(file)}
function setupCNNV93(){if(!$('cnnInputCanvas'))return;demoImageV93();runCNNV93();$('cnnLoadImageBtn').onclick=()=>$('cnnImageInput').click();$('cnnImageInput').onchange=e=>{loadCNNImageV93(e.target.files?.[0]);e.target.value=''};$('cnnDemoImageBtn').onclick=()=>{demoImageV93();runCNNV93()};$('cnnRunBtn').onclick=runCNNV93;$('cnnKernelSelect').onchange=()=>{renderKernelV93();runCNNV93()};$('cnnPadding').onchange=runCNNV93;$('cnnStride').onchange=runCNNV93}

const _v93ActivateTab=window.activateTab;
window.activateTab=function(tab){_v93ActivateTab(tab);if(tab==='concepts')setTimeout(renderActivationExplorerV93,20);if(tab==='cnn')setTimeout(()=>{renderKernelV93();if(!V93.cnn.matrix)demoImageV93();runCNNV93()},20)};

function setupV93(){
  if(typeof V9!=='undefined')V9.viewTitles.cnn=['CNN · VISIÓN ARTIFICIAL','Convolución, filtros y mapas de activación'];
  patchLayerActivationSelectsV93();
  const ex=$('activationExplorerSelect');if(ex){ex.value='sigmoid';ex.onchange=renderActivationExplorerV93}
  if($('applyActivationToAllBtn'))$('applyActivationToAllBtn').onclick=applyActivationToNetworkV93;if($('activationInfoBtn'))$('activationInfoBtn').onclick=openActivationModalV93;
  document.querySelectorAll('[data-course-scroll]').forEach(b=>b.onclick=()=>{activateTab('concepts');setTimeout(()=>$(b.dataset.courseScroll)?.scrollIntoView({behavior:'smooth',block:'center'}),80)});
  ['metricSpecificity','metricBalancedAccuracy'].forEach(id=>{const el=$(id);if(el)el.onchange=()=>{const t=currentNet()?.trained;if(!t)return;const m=t.model,d=m.multiclass?prepareMulticlassRowsV91(State.split.test.length?State.split.test:State.split.val,m.stats).data:prepareRows(State.split.test.length?State.split.test:State.split.val,m.stats).data;renderEvaluationMetrics(m,d)}});
  setupCNNV93();renderActivationExplorerV93();
}
document.addEventListener('DOMContentLoaded',setupV93,{once:true});
